-- Generated by scripts/catalog/generate.mjs from src/core/__fixtures__/layouts.json; do not edit by hand.
-- The same cases run against src/core/grid.ts in Vitest, so the client and save_layout agree.
begin;
select plan(20);
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[]'::jsonb, 8) e), null::text, 'empty room');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"rug_stripe","x":1,"z":1,"rot":0},{"item_id":"desk_oak","x":2,"z":3,"rot":2},{"item_id":"chair_wood","x":2,"z":2,"rot":0},{"item_id":"lamp_floor","x":1,"z":3,"rot":0},{"item_id":"plant_pot","x":0,"z":0,"rot":0},{"item_id":"window_double","x":2,"z":0,"rot":0}]'::jsonb, 8) e), null::text, 'starter personal room');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"rug_stripe","x":0,"z":0,"rot":0},{"item_id":"desk_oak","x":1,"z":1,"rot":0}]'::jsonb, 8) e), null::text, 'furniture may stand on a rug');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"desk_oak","x":3,"z":3,"rot":0},{"item_id":"chair_wood","x":3,"z":3,"rot":1}]'::jsonb, 8) e), 'overlap@1'::text, 'two pieces of furniture on one cell');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"desk_oak","x":4,"z":0,"rot":0},{"item_id":"bookshelf","x":3,"z":0,"rot":0}]'::jsonb, 8) e), 'overlap@1'::text, 'a two-wide shelf overlapping a desk');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"bookshelf","x":0,"z":6,"rot":1}]'::jsonb, 8) e), null::text, 'rotated shelf runs along z');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"bookshelf","x":0,"z":7,"rot":1}]'::jsonb, 8) e), 'out_of_bounds@0'::text, 'rotated shelf off the far edge');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"desk_oak","x":-1,"z":0,"rot":0}]'::jsonb, 8) e), 'out_of_bounds@0'::text, 'negative cell');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"rug_long","x":5,"z":0,"rot":0}]'::jsonb, 8) e), 'out_of_bounds@0'::text, 'a big rug past the edge of a small room');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"rug_long","x":5,"z":0,"rot":0}]'::jsonb, 12) e), null::text, 'the big rug fits a shared room');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"throne","x":0,"z":0,"rot":0}]'::jsonb, 8) e), 'unknown_item@0'::text, 'unknown item');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"beret","x":0,"z":0,"rot":0}]'::jsonb, 8) e), 'unknown_item@0'::text, 'an accessory is not furniture');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"desk_oak","x":1.5,"z":0,"rot":0}]'::jsonb, 8) e), 'bad_position@0'::text, 'half a cell');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"desk_oak","x":1,"z":0,"rot":4}]'::jsonb, 8) e), 'bad_position@0'::text, 'rotation out of range');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"window_double","x":1,"z":0,"rot":0},{"item_id":"window_double","x":0,"z":1,"rot":1}]'::jsonb, 8) e), null::text, 'windows on both walls');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"window_double","x":1,"z":0,"rot":0},{"item_id":"poster","x":2,"z":0,"rot":0}]'::jsonb, 8) e), 'overlap@1'::text, 'two wall items in one slot');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"poster","x":2,"z":3,"rot":0}]'::jsonb, 8) e), 'bad_wall_slot@0'::text, 'a wall item off the wall');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"clock","x":0,"z":0,"rot":2}]'::jsonb, 8) e), 'bad_wall_slot@0'::text, 'a wall item turned to face away');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"fairy_lights","x":6,"z":0,"rot":0}]'::jsonb, 8) e), 'out_of_bounds@0'::text, 'fairy lights past the end of the wall');
select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('[{"item_id":"bed","x":0,"z":0,"rot":0}]'::jsonb, 8) e), null::text, 'a bed in the corner');
select * from finish();
rollback;
