// Keeps SQL in step with the JSON the app uses (SPEC §15 M5):
//  - the catalog seed block inside the M5 migration, from src/content/catalog.json
//  - the pgTAP layout parity test, from src/core/__fixtures__/layouts.json
// Usage: node scripts/catalog/generate.mjs --write   (or --check: exit 1 if anything is stale)
import { readFileSync, writeFileSync } from 'node:fs'

const MIGRATION = 'supabase/migrations/20261011000000_m5_coins_shop.sql'
const FIXTURE_TEST = 'supabase/tests/database/08_m5_layout_fixtures.test.sql'
const BEGIN = '-- catalog:begin'
const END = '-- catalog:end'

const q = (v) =>
  v === null || v === undefined
    ? 'null'
    : typeof v === 'number' || typeof v === 'boolean'
      ? String(v)
      : `'${String(v).replace(/'/g, "''")}'`

export function seedBlock(catalog) {
  const rows = [
    ...catalog.items.map((i) =>
      [
        i.id,
        i.name,
        i.category,
        i.price,
        i.footprint[0],
        i.footprint[1],
        i.layer,
        i.model,
        Boolean(i.seat),
        null,
      ]
        .map(q)
        .join(', '),
    ),
    ...catalog.accessories.map((a) =>
      [a.id, a.name, 'accessory', a.price, null, null, null, null, false, a.slot].map(q).join(', '),
    ),
  ]
  const starter = []
  for (const scope of ['personal', 'shared']) {
    const counts = new Map()
    for (const id of catalog.starter[scope]) counts.set(id, (counts.get(id) ?? 0) + 1)
    for (const [id, n] of counts) starter.push([scope, id, n].map(q).join(', '))
  }
  return [
    `${BEGIN} (generated by scripts/catalog/generate.mjs from src/content/catalog.json; do not edit by hand)`,
    'insert into public.catalog_items (id, name, category, price, footprint_w, footprint_d, layer, model, seat, slot) values',
    rows.map((r) => `  (${r})`).join(',\n'),
    'on conflict (id) do update set name = excluded.name, category = excluded.category, price = excluded.price,',
    '  footprint_w = excluded.footprint_w, footprint_d = excluded.footprint_d, layer = excluded.layer,',
    '  model = excluded.model, seat = excluded.seat, slot = excluded.slot;',
    'delete from public.catalog_starter;',
    'insert into public.catalog_starter (scope, item_id, qty) values',
    starter.map((r) => `  (${r})`).join(',\n') + ';',
    END,
  ].join('\n')
}

export function fixtureTest(fixtures) {
  const lines = [
    '-- Generated by scripts/catalog/generate.mjs from src/core/__fixtures__/layouts.json; do not edit by hand.',
    '-- The same cases run against src/core/grid.ts in Vitest, so the client and save_layout agree.',
    'begin;',
    `select plan(${fixtures.cases.length});`,
  ]
  for (const c of fixtures.cases) {
    const json = JSON.stringify(c.layout).replace(/'/g, "''")
    const expected = c.error === null ? 'null' : q(`${c.error}@${c.index}`)
    lines.push(
      `select is((select e ->> 'error' || '@' || (e ->> 'index') from private.layout_error('${json}'::jsonb, ${c.size}) e), ${expected}::text, ${q(c.name)});`,
    )
  }
  lines.push('select * from finish();', 'rollback;', '')
  return lines.join('\n')
}

function main() {
  const mode = process.argv[2]
  const catalog = JSON.parse(readFileSync('src/content/catalog.json', 'utf8'))
  const fixtures = JSON.parse(readFileSync('src/core/__fixtures__/layouts.json', 'utf8'))
  const migration = readFileSync(MIGRATION, 'utf8')
  const a = migration.indexOf(BEGIN)
  const b = migration.indexOf(END)
  if (a < 0 || b < 0) throw new Error(`markers missing in ${MIGRATION}`)
  const nextMigration = migration.slice(0, a) + seedBlock(catalog) + migration.slice(b + END.length)
  const nextTest = fixtureTest(fixtures)
  if (mode === '--write') {
    writeFileSync(MIGRATION, nextMigration)
    writeFileSync(FIXTURE_TEST, nextTest)
    return
  }
  let current = ''
  try {
    current = readFileSync(FIXTURE_TEST, 'utf8')
  } catch {
    current = ''
  }
  if (nextMigration !== migration || nextTest !== current) {
    console.error('Generated SQL is stale: run node scripts/catalog/generate.mjs --write')
    process.exit(1)
  }
}

if (process.argv[1]?.endsWith('generate.mjs')) main()
