// Every user-facing string lives here (SPEC §16).
export const copy = {
  tabs: { home: 'Home', rooms: 'Rooms', myRoom: 'My Room', stats: 'Stats', profile: 'You' },
  common: {
    back: 'Back',
    next: 'Next',
    save: 'Save',
    skip: 'Skip',
    loading: 'Loading…',
    signOut: 'Sign out',
    close: 'Close',
    skipToMain: 'Skip to content',
  },
  errors: {
    generic: 'Something went wrong. Try again.',
    offline: 'Couldn’t reach Studyroom. Check your connection and try again.',
    schema_outdated:
      'This part of Studyroom needs a database update that hasn’t been applied yet. (Builder: run supabase db push.)',
    handle_taken: 'That handle is taken. Try another.',
    invalid_handle: 'Handles are 3–20 letters, numbers or underscores.',
    invalid_display_name: 'Names are 1–30 characters.',
    consent_required: 'Your account is waiting for a parent’s OK.',
    room_not_allowed: 'You can’t study in that room.',
    invalid_note: 'Notes are 3–140 characters.',
    note_not_possible: 'That note can’t be added any more.',
    load_failed: 'Couldn’t reach the server. Check your connection.',
    inappropriate_text: 'Let’s keep it friendly. Try different words.',
    room_not_found: 'That room doesn’t exist, or its invite link changed.',
    room_full: 'That room is full (50 people).',
    too_many_rooms: 'You’re in 20 rooms already. Leave one first.',
    too_many_rooms_created: 'You’ve created 10 rooms already.',
    banned_from_room: 'You were removed from this room.',
    rate_limited: 'Slow down a little and try again in a minute.',
    owner_must_transfer: 'Hand the room to someone else before you leave.',
    not_allowed: 'Only the room’s owner or mods can do that.',
    invalid_room_name: 'Room names are 3–40 characters.',
    invalid_reason: 'Give a short reason (3–140 characters).',
    invalid_email: 'That doesn’t look like an email address.',
    parent_email_is_yours: 'Use your parent’s or guardian’s email, not yours.',
    too_many_requests: 'You’ve asked three times. Check with your parent directly.',
    consent_not_found: 'This link isn’t valid any more.',
    consent_expired: 'This request expired. Your child can ask again from the app.',
    account_banned: 'This account can’t use Studyroom.',
    sync_in_break: 'The room is on a shared break. Join the next focus.',
    sync_phase_ending: 'This focus is nearly over. Join the next one.',
    sync_pomodoro_only: 'This room runs a shared pomodoro, so the stopwatch is off here.',
    invalid_plan: 'Pick a focus length between 5 and 120 minutes.',
    blocked: 'Something is in the way.',
    not_enough_coins: 'Not enough coins yet.',
    already_owned: 'You already have this.',
    item_not_owned: 'Some of those things aren’t yours to place.',
    invalid_layout: 'Something overlaps or sticks out. Move it and try again.',
    accessory_not_owned: 'Buy that accessory in the shop first.',
    invalid_amount: 'Give between 1 and 10,000 coins.',
    invalid_station: 'That station isn’t available.',
    sync_room_move: 'This room runs a shared pomodoro. End your timer here and join its next focus instead.',
    no_active_session: 'Your timer already ended.',
    mixed_ages: 'Everyone in the room needs to be in the same age group to list it in Discover.',
    invalid_style: 'That wall or floor isn’t available.',
    invalid_push_endpoint: 'This browser’s notification service isn’t supported.',
  },
  loadError: {
    body: 'Your sign-in worked, but loading your profile failed. Try again in a moment.',
    schemaTitle: 'The database isn’t set up yet',
    schemaBody:
      'Sign-in worked, but the Studyroom tables aren’t in this Supabase project. Apply the migrations (supabase db push), then try again.',
    retry: 'Try again',
  },
  unconfigured: {
    title: 'Not connected yet',
    body: 'This build has no Supabase project. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local (or to the Vercel project settings) and rebuild.',
  },
  signIn: {
    title: 'Come study with us',
    lead: 'A cozy room you share with friends. See who’s studying right now.',
    google: 'Continue with Google',
    or: 'or',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    emailButton: 'Email me a sign-in link',
    sent: (email: string) => `Check ${email} for a sign-in link. You can close this tab.`,
    privacy: 'No ads, no tracking. Your email is only used to sign you in.',
  },
  onboarding: {
    step: (n: number, of: number) => `Step ${n} of ${of}`,
    age: {
      title: 'A couple of quick questions',
      countryLabel: 'Where do you live?',
      ageLabel: 'How old are you?',
      brackets: { under_13: 'Under 13', '13': '13', '14': '14', '15': '15', '16-17': '16–17', '18+': '18+' },
      why: 'Some countries need a parent’s OK below a certain age. We don’t store your birthday.',
    },
    name: {
      title: 'What should people call you?',
      handleLabel: 'Handle',
      handleHint: 'Lowercase letters, numbers and _. Your friends find you with it.',
      displayLabel: 'Display name',
      displayHint: 'Shown above your bean.',
      errors: {
        too_short: 'At least 3 characters.',
        too_long: 'Too long.',
        bad_chars: 'Only a–z, 0–9 and _.',
        empty: 'Pick a name.',
      },
    },
    bean: {
      title: 'Make your bean',
      skin: 'Skin',
      hair: 'Hair',
      body: 'Bottoms',
      top: 'Top',
      accent: 'Accessories',
      hairStyle: 'Hairstyle',
      styles: { short: 'Short', long: 'Long', curly: 'Curly', bun: 'Bun' },
      topStyle: 'Top',
      tops: { tee: 'Tee', hoodie: 'Hoodie', stripes: 'Stripes', collar: 'Collar' },
      bottomStyle: 'Bottoms',
      bottoms: { trousers: 'Trousers', shorts: 'Shorts', skirt: 'Skirt' },
      accessoriesLabel: 'Accessories',
      accessories: {
        beanie: 'Beanie',
        cap: 'Cap',
        bow: 'Bow',
        glasses: 'Glasses',
        headphones: 'Headphones',
        scarf: 'Scarf',
        beret: 'Beret',
        cat_ears: 'Cat ears',
        flower: 'Flower clip',
        shades: 'Sunglasses',
      },
      tabs: { face: 'Face', style: 'Style', colors: 'Colors' },
      expressionLabel: 'Expression',
      expressions: {
        happy: 'Happy',
        joyful: 'Joyful',
        calm: 'Calm',
        focused: 'Focused',
        sleepy: 'Sleepy',
        surprised: 'Surprised',
        cheeky: 'Cheeky',
        cat: 'Cat smile',
      },
      randomize: 'Surprise me',
      finish: 'Finish',
    },
  },
  blocked: {
    title: 'Studyroom is for ages 13 and up',
    body: 'Sorry! We’ve removed the sign-in you just made. Come back when you’re 13.',
  },
  waiting: {
    title: 'Waiting for your parent',
    body: 'Where you live, a parent or guardian needs to say OK before you can use Studyroom. We’ll email them a link to review and decide.',
    emailLabel: 'Parent or guardian’s email',
    send: 'Send the request',
    resend: 'Send again',
    sent: (email: string) => `Sent to ${email}. It can take a few minutes; ask them to check spam too.`,
    expiry: 'If nobody answers within 7 days, this account is deleted.',
    deleteInstead: 'Delete my account instead',
  },
  consent: {
    title: (name: string) => `${name} would like to use Studyroom`,
    lead: 'Studyroom is a study timer where friends see each other studying in shared rooms.',
    collect: [
      'We collect: an email address (only to sign in), a display name, a cartoon avatar, and study sessions (start time, length, an optional note).',
      'Room members see display names, avatars and study minutes. There is no chat.',
      'No ads, no tracking, no selling data. You can withdraw at any time, which deletes the account.',
    ],
    agree: 'I’m their parent or guardian and I agree',
    decline: 'Decline',
    withdraw: 'Withdraw consent and delete the account',
    granted: 'Thank you. The account is active.',
    deleted: 'Done. The account and its data have been deleted.',
    expired: 'This request has expired.',
    privacy: 'Read the full privacy page',
  },
  home: {
    greeting: { day: 'Good to see you.', night: 'The lamps are on.' },
    hi: (name: string) => `Hi, ${name}.`,
    today: 'Today',
    thisWeek: 'This week',
    streak: 'Day streak',
    streakDays: (n: number) => (n === 1 ? '1 day' : `${n} days`),
    soloTitle: 'Study solo',
    soloBody: 'Your own room, your own timer.',
    soloButton: 'Open my room',
    roomsHeading: 'Your rooms',
    allRooms: 'All rooms',
    emptyTitle: 'No shared rooms yet',
    emptyBody: 'Rooms are where you study with friends. Make one and send the link, or join with a code.',
    createRoom: 'Create room',
    joinWithCode: 'Join with code',
    weekRank: (n: number) => `#${n} this week`,
    studyingNow: (n: number) =>
      n === 0 ? 'Nobody studying' : n === 1 ? '1 studying now' : `${n} studying now`,
    members: (n: number) => (n === 1 ? '1 member' : `${n} members`),
    createTitle: 'Create a room',
    nameLabel: 'Room name',
    namePlaceholder: 'e.g. IB Chem crew',
    create: 'Create',
    joinTitle: 'Join a room',
    codeLabel: 'Invite code or link',
    join: 'Join',
    cancel: 'Cancel',
  },
  you: {
    customize: 'Customize bean',
  },
  stats: {
    title: 'Stats',
    hint: 'All your study time, all time. Only you see this page.',
    totals: 'Totals',
    total: 'Total focus',
    sessions: 'Sessions',
    pomodoros: 'Full pomodoros',
    streakNow: 'Current streak',
    streakBest: 'Best streak',
    longest: 'Longest session',
    last30: 'Last 30 days',
    year: 'Your year',
    less: 'Less',
    more: 'More',
    hoursTitle: 'Time of day',
    hourRange: (h: number) => `${h}:00–${h + 1}:00`,
    weekdaysTitle: 'Day of the week',
    monthsTitle: 'Last 12 months',
    roomsTitle: 'Where you study',
    empty: 'Finish a session and your stats start here.',
  },
  rooms: {
    title: 'Rooms',
    hint: 'Be in as many rooms as you like. You study in one at a time, and can move between them.',
    tabs: { mine: 'Your rooms', discover: 'Discover' },
    youreHere: 'You’re studying here',
    discoverHint:
      'Rooms their owners chose to list, for people your age. You see who’s inside after you join.',
    discoverEmptyTitle: 'No rooms to discover yet',
    discoverEmptyBody:
      'When room owners list their rooms, they show up here. You can list yours from its settings.',
    studyingIn: (room: string) => `You’re studying in ${room}.`,
    anotherRoom: 'another room',
    moveHere: 'Move here',
    goBack: 'Go back there',
    join: 'Join',
    joinNamed: (name: string) => `Join ${name}`,
    listTitle: 'List in Discover',
    listHint:
      'People your age can find this room by its name and join without a link. They won’t see who’s in it until they join.',
    mixedAges: 'Everyone in the room needs to be in the same age group to list it.',
  },
  invite: {
    title: (name: string) => `Join ${name}`,
    members: (n: number) => (n === 1 ? '1 member' : `${n} members`),
    studyingNow: 'Studying right now',
    nobody: 'Nobody’s studying right now. Be the first.',
    join: 'Join the room',
    signInFirst: 'Sign in to join',
    notFound: 'This invite link doesn’t work any more. Ask for a new one.',
  },
  theme: {
    title: 'Theme',
    lightOrDark: 'Light or dark',
    mode: { auto: 'Auto', light: 'Light', dark: 'Dark' },
    autoHint: 'Auto follows the time of day: light by day, lamp-lit at night.',
  },
  room: {
    soloBadge: 'Just you',
    present: (n: number) => (n === 1 ? '1 here' : `${n} here`),
    alone: (time: string) => `You’ve got the room to yourself · ${time}`,
    nightOwl: (time: string) => `Night owl — you’ve had the room to yourself for ${time}`,
    emptyRoom: 'Nobody’s studying yet. Start a timer and you’ll be the first one here.',
    sat: (name: string) => `${name} just sat down`,
    onBreak: 'On a break',
    focusingLabel: 'Focusing',
    menu: 'Room menu',
    noWebgl: 'This device can’t show the 3D room, so here’s the list instead.',
    timerLabel: 'Timer',
    typeLabel: 'Timer type',
    lengthLabel: 'Focus length',
    studyingNow: 'Studying now',
    nudgeSent: (name: string) => `Nudge sent to ${name}`,
    reactionLabel: (emoji: string) => `Send ${emoji}`,
    invite: 'Invite friends',
    copyLink: 'Copy invite link',
    copied: 'Link copied',
    share: 'Share',
    settings: 'Room settings',
    leave: 'Leave room',
    leaveConfirm: 'Leave this room? Your study time stays on its boards.',
    tabs: { leaderboard: 'Leaderboard', radio: 'Radio', members: 'Members' },
    boards: { live: 'Now', week: 'Week', alltime: 'All-time', lifetime: 'Lifetime' },
    boardHint: {
      live: 'Minutes in the current sitting.',
      week: 'Minutes in this room since Monday.',
      alltime: 'Every minute in this room.',
      lifetime: 'Every minute anywhere, for people in this room.',
    },
    boardEmpty: 'No minutes yet.',
    you: 'you',
    reactions: 'Reactions',
    nudge: 'Nudge',
    nudged: (name: string) => `${name} nudged you 👋`,
    reacted: (name: string, emoji: string) => `${name} ${emoji}`,
    block: 'Block',
    unblock: 'Unblock',
    report: 'Report',
    removed: 'You were removed from this room.',
    freeDesk: 'free desk',
    sceneLoading: 'Setting up the room…',
    sceneLabel: (name: string) => `${name}, isometric room view`,
    label: (name: string, state: string, clock: string) => `${name}, ${state}, ${clock}`,
    presentNow: 'Here now',
    everyone: 'Everyone',
    onlineIdle: (names: string[]) =>
      `${names.join(', ')} ${names.length === 1 ? 'is' : 'are'} here, not studying yet.`,
    sittingDots: (n: number) => (n === 1 ? '1 pomodoro this sitting' : `${n} pomodoros this sitting`),
    todayTotal: (time: string) => `Today: ${time}`,
    pomodoro: 'Pomodoro',
    stopwatch: 'Stopwatch',
    minutes: (m: number) => `${m} min`,
    statusLabel: 'What are you working on?',
    statusPlaceholder: 'e.g. HL Chem IA — data analysis',
    start: 'Start',
    end: 'End',
    endEarly: 'End early',
    focusing: 'Focusing',
    breakTitle: (m: number) => `Break · ${m} min`,
    breakBody: 'Stretch, drink some water, look out a window.',
    startNext: 'Start next focus',
    skipBreak: 'Skip break',
    checkinTitle: 'Still studying?',
    checkinBody: (mmss: string) => `Tap within ${mmss} or this session ends where you left it.`,
    checkinButton: 'Yes, still here',
  },
  profileSheet: {
    weekMinutes: (m: string) => `${m} this week`,
    roleOwner: 'Owner',
    roleMod: 'Mod',
    makeMod: 'Make mod',
    removeMod: 'Remove mod',
    makeOwnerConfirm: (name: string) =>
      `Make ${name} the owner? You’ll become a mod and can’t undo this yourself.`,
    makeOwner: 'Make owner',
    remove: 'Remove from room',
    removeConfirm: (name: string) => `Remove ${name}? They can’t rejoin with the link.`,
    sessions: 'Recent sessions',
    noSessions: 'No sessions in this room yet.',
    void: 'Void',
    voidReason: 'Why? (shown to them)',
    voided: 'Voided',
  },
  reportSheet: {
    title: (name: string) => `Report ${name}`,
    reasonLabel: 'What’s wrong?',
    reasons: {
      harassment: 'Being mean or harassing',
      inappropriate_name: 'Inappropriate name or text',
      cheating: 'Cheating on the timer',
      unfair_void: 'An unfair void',
      other: 'Something else',
    },
    noteLabel: 'Anything else? (optional)',
    send: 'Send report',
    sent: 'Thanks. The room’s owner and the Studyroom admin will look at it.',
  },
  settingsSheet: {
    title: 'Room settings',
    rename: 'Room name',
    save: 'Save',
    newLinkConfirm: 'Make a new invite link? The old link stops working straight away.',
    newLink: 'Make a new invite link',
    newLinkHint: 'The old link stops working.',
    reports: 'Open reports',
    noReports: 'No open reports.',
  },
  endSheet: {
    title: 'Nice work',
    focused: (mmss: string) => `You focused for ${mmss}.`,
    noteLabel: 'What did you get done?',
    notePlaceholder: 'e.g. finished the data table for Q3',
    noteHint: 'Private to you. 3–140 characters.',
    saveNote: 'Save note',
    later: 'Later',
  },
  myRoom: {
    title: 'My Room',
    body: 'Your own little room. Save a note after you study to earn coins, then make it yours in Decorate.',
    studyHere: 'Study here',
    editBean: 'Change bean',
    beanTitle: 'Your bean',
    save: 'Save',
    saved: 'Bean updated',
    sceneLabel: (name: string) => `${name}’s room`,
  },
  profile: {
    title: 'Profile',
    lifetime: 'Lifetime',
    thisWeek: 'This week',
    streak: 'Day streak',
    historyTitle: 'History',
    historyEmpty: 'Finished sessions show up here.',
    addNote: 'Add a note',
    voided: 'Voided',
    privacy: 'Privacy',
    account: 'Your account',
    weekChart: 'Focus, last 7 days',
    export: 'Download my data',
    deleteAccount: 'Delete my account',
    deleteConfirm: (handle: string) =>
      `This deletes your account, sessions and notes for good. Type ${handle} to confirm.`,
    deleteButton: 'Delete forever',
    blocked: 'Blocked people',
    noneBlocked: 'Nobody blocked.',
    admin: 'Moderation queue',
  },
  coins: {
    label: 'Coins',
    balance: (n: number) => `${n} ${n === 1 ? 'coin' : 'coins'}`,
    debt: 'A voided session took back more than you had. New coins fill this first.',
    earned: (n: number) => `+${n} ${n === 1 ? 'coin' : 'coins'}`,
    forNote: (n: number) => `Save a note to earn ${n} ${n === 1 ? 'coin' : 'coins'}`,
    today: (n: number, cap: number) => `${n} of ${cap} earned today`,
    bank: (n: number) => `Room bank: ${n} ${n === 1 ? 'coin' : 'coins'}`,
    donate: 'Give coins to the room',
    donateTitle: 'Give to the room bank',
    donateHint: 'Owners and mods spend the bank on things for the room. Studying here fills it too.',
    amount: 'How many coins?',
    give: 'Give',
    given: (n: number) => `You gave ${n} ${n === 1 ? 'coin' : 'coins'}`,
  },
  shop: {
    title: 'Shop',
    roomTitle: (room: string) => `Shop for ${room}`,
    tabs: { furniture: 'Furniture', decor: 'Decor', wall: 'Walls', accessory: 'Accessories' },
    buy: 'Buy',
    owned: (n: number) => (n === 1 ? 'You have 1' : `You have ${n}`),
    roomOwned: (n: number) => `The room has ${n}`,
    bought: (name: string) => `${name} is yours`,
    roomBought: (name: string) => `${name} added to the room`,
    wear: 'Wear it from Change bean.',
    ownedAccessory: 'Owned',
    back: 'Back',
    hint: 'Coins come from saving notes after you study.',
    roomHint: 'Bought with the room bank. Anyone can give to it.',
  },
  decor: {
    edit: 'Decorate',
    editRoom: 'Decorate room',
    roomShop: 'Room shop',
    tray: 'Your things',
    roomTray: 'The room’s things',
    trayEmpty: 'Everything is placed. Buy more in the shop.',
    rotate: 'Rotate',
    place: 'Place',
    move: 'Move',
    remove: 'Put away',
    save: 'Save',
    cancel: 'Cancel',
    saved: 'Room saved',
    discard: 'Leave without saving? Your changes will be lost.',
    keysHint: 'With a thing picked: arrow keys move it, R turns it, Enter places it.',
    layouts: 'Layouts',
    layoutsHint: 'Start from a ready-made room. Nothing changes until you save.',
    finishes: 'Walls and floor',
    walls: 'Walls',
    floors: 'Floor',
    placeHint: 'Tap the floor to place it. Tap a placed thing to move, turn or put it away.',
    blocked: 'Something is in the way.',
    reset: 'Start from the default room',
  },
  radio: {
    tab: 'Radio',
    title: 'Radio',
    play: 'Play',
    pause: 'Pause',
    mute: 'Mute',
    unmute: 'Unmute',
    volume: 'Volume',
    stations: 'Station',
    pickHint: 'Everyone in the room hears the same station. You set your own volume.',
    personalHint: 'Pick a station for your own room.',
    ownerPicks: 'The room’s owner or a mod picks the station.',
    comingSoon: 'Soon',
    generatedArtist: 'Made live in your browser',
    generatedLine: 'Made live in your browser. Nothing to download.',
    silenceLine: 'Just you and your thoughts.',
    changed: (name: string) => `Room station: ${name}`,
    pill: (name: string, playing: boolean) => (playing ? `Pause ${name}` : `Play ${name}`),
  },
  visit: {
    title: (name: string) => `${name}’s room`,
    button: 'Visit room',
    back: 'Back',
    notAllowed: 'You can only visit people you share a room with.',
  },
  push: {
    askTitle: 'Get a ping when it’s break time?',
    askTitleRoom: 'Turn on notifications?',
    askBody:
      'Studyroom can tell you when a focus block ends, when your stopwatch needs a check-in, and when friends start studying in rooms you choose. Nothing else.',
    allow: 'Turn on',
    notNow: 'Not now',
    installTitle: 'Add Studyroom to your Home Screen',
    installBody: 'On iPhone and iPad, notifications only work for apps on the Home Screen.',
    installSteps: [
      'Tap the Share button in Safari.',
      'Choose “Add to Home Screen”.',
      'Open Studyroom from your Home Screen and turn notifications on.',
    ],
    deniedTitle: 'Notifications are blocked',
    deniedBody: 'Allow notifications for this site in your browser or phone settings, then try again.',
    ok: 'OK',
    section: 'Notifications',
    device: {
      on: 'On for this device.',
      off: 'Off for this device.',
      ask: 'Off for this device.',
      denied: 'Blocked in your browser settings.',
      needs_install: 'Add Studyroom to your Home Screen to get notifications.',
      unsupported: 'This browser can’t show notifications.',
    },
    turnOn: 'Turn on',
    turnOff: 'Turn off',
    types: { phase_end: 'Break time', checkin: 'Stopwatch check-ins' },
    roomToggle: 'Tell me when someone starts studying here',
    roomToggleHint: 'At most once every 2 hours.',
  },
  sync: {
    badge: 'Shared pomodoro',
    focus: (left: string, n: number) =>
      `Focus · ${left} left · ${n === 0 ? 'be the first' : `${n} focusing`}`,
    breakTogether: (left: string) => `Break together · ${left}`,
    joinNow: 'Join this focus',
    joinNext: (inTime: string) => `Join the next focus in ${inTime}`,
    waiting: (inTime: string) => `You’re in. Starting in ${inTime}…`,
    cancelWait: 'Cancel',
    breakHint: 'Shared break: say hi with a reaction.',
    nudgeMuted: 'Nudges are off during a shared focus.',
    settingsTitle: 'Shared pomodoro',
    settingsHint: 'Everyone in the room runs the same focus and break.',
    on: 'On',
    off: 'Off',
    lengths: (f: number, b: number) => `${f} / ${b} min`,
  },
  metrics: {
    title: 'Usage',
    hint: 'Other people only (admins excluded). Totals, never names or notes.',
    people: 'People',
    wau: 'Active this week',
    hours: 'Hours this week',
    dau: 'Active today',
    hoursChart: 'Hours studied per week',
    weeklyTable: 'Weekly',
    retentionTable: 'Retention by signup week',
    cols: {
      week: 'Week of',
      wau: 'Active',
      hours: 'Hours',
      sessions: 'Sessions',
      perUser: 'Per person',
      sync: 'Shared pomodoro',
      shared: 'Room pomodoro',
      solo: 'Solo pomodoro',
      signups: 'Sign-ups',
      size: 'Signed up',
      d1: 'D1',
      d7: 'D7',
      d30: 'D30',
    },
    csv: 'Download CSV',
    empty: 'No data yet.',
  },
  admin: {
    page: 'Admin',
    title: 'Moderation queue',
    empty: 'No open reports.',
    dismiss: 'Dismiss',
    removeContent: 'Remove content',
    ban: 'Ban user',
    deleteRoom: 'Delete room',
    confirm: (action: string) => `${action}? This can’t be undone.`,
  },
  privacy: {
    title: 'Privacy',
    updated: 'Last updated 10 October 2026',
    sections: [
      {
        h: 'What Studyroom is',
        p: [
          'A study timer where friends can see each other studying in shared rooms. It is built by a student, for students. There are no ads and we never sell data.',
        ],
      },
      {
        h: 'What we collect',
        p: [
          'Your email address, only to sign you in. Nobody else sees it.',
          'Your handle, display name and cartoon avatar (colors, hairstyle, outfit and accessories).',
          'Your country and an age range (not your birthday), so we know whether a parent needs to agree first.',
          'Your timezone (so weeks and days start at your midnight) and your settings, such as theme, timer length and which notifications you want.',
          'Your study sessions: when they started, how long they were, what you wrote as your status line, and any note you add afterwards.',
          'The rooms you are in, people you block, and reports you send. If you own a room and list it in Discover, that choice is stored too.',
          'Coins: every coin you earn, spend or give to a room, the things you and your rooms own, and how your rooms are decorated. Coins are pretend money for decorating; they can’t be bought with real money or turned into it.',
          'Simple usage counts (for example “a session was completed”), with no free text in them.',
          'If a parent needs to agree: their email address, only until they answer (or for up to 7 days), then just a scrambled (hashed) copy and when they agreed.',
          'If you turn notifications on: an address from your browser’s notification service for each device, and which rooms you want “room is active” alerts for. Turning notifications off or signing out on a device removes its address.',
        ],
      },
      {
        h: 'Who sees what',
        p: [
          'People in a room with you see your display name, handle, avatar, your status line while you study, and your minutes on that room’s leaderboards. They can also visit your own room to see how you decorated it, and see the room’s coin bank (not who gave what).',
          'If a room’s owner lists it in Discover, people in the same age group (13–15, 16–17 or 18+) can see its name and how many people are in it and studying, and can join it. They see who is inside only after joining. A room with members of different age groups can’t be listed.',
          'Your stats page is only for you. It is worked out from your own sessions.',
          'Your notes are private to you. Nobody outside a room can see who is in it, except a short preview (room name, member count, and who is studying right now) shown to anyone with the invite link.',
          'The builder of Studyroom can see reports and act on them, and can see overall usage numbers. Numbers used in a university application are totals only, never names or notes.',
        ],
      },
      {
        h: 'Services we use',
        p: [
          'Supabase stores the data and runs sign-in. Vercel serves the app. Resend sends the parent-consent email. Notifications travel through your browser’s own service (Google, Apple, Mozilla or Microsoft) and are encrypted so only your device can read them. Fonts and everything else are served by Studyroom itself; there are no trackers or analytics companies.',
        ],
      },
      {
        h: 'Your choices',
        p: [
          'Download everything we have about you from Profile → Download my data.',
          'Delete your account from Profile → Delete my account. It is removed for good straight away, including sessions and notes. Rooms you own pass to another member.',
          'Usage counts that no longer point to a person are kept for up to 400 days, then deleted.',
          'Your coins, the things you own and how your rooms look are kept until you delete your account. Coins you gave to a shared room stay in its bank afterwards, but no longer point to you.',
          'The radio’s station, volume and mute, and the station for your own room, are remembered only on your device.',
          'Notifications waiting to be sent are deleted after 7 days. To stop people guessing invite codes, we briefly count requests per account or internet address; those counts are deleted after a day.',
          'Your sessions and notes are kept until you delete them with your account.',
        ],
      },
      {
        h: 'Children and parents',
        p: [
          'Studyroom is for ages 13 and up. Where the law asks for it (for example under 16 in Germany or the Netherlands), a parent or guardian must agree by email first. If nobody answers within 7 days, the account is deleted. A parent can withdraw at any time from the link in that email, which deletes the account.',
        ],
      },
    ],
  },
  notFound: { title: 'This room does not exist', back: 'Back home' },
  offline: {
    banner: 'You’re offline. A running timer keeps going; everything else catches up when you’re back.',
    retry: 'Try again',
    failed: 'Couldn’t load this. Check your connection and try again.',
    coldStart: 'Studyroom needs a connection to open. It will try again by itself when you’re back online.',
  },
  routeError: {
    title: 'Something went wrong',
    body: 'This screen hit a snag. Reloading usually fixes it.',
    updateTitle: 'Studyroom was updated',
    updateBody: 'Reload to get the new version.',
    offlineTitle: 'You’re offline',
    offlineBody: 'This screen needs a connection the first time. Try again when you’re back online.',
    reload: 'Reload',
    home: 'Go home',
  },
} as const

/** Message for an RPC error code; unknown codes get the generic message. */
export function errorMessage(code: string): string {
  return (copy.errors as Record<string, string | undefined>)[code] ?? copy.errors.generic
}
