// Every user-facing string lives here (SPEC §16).
export const copy = {
  tabs: { home: 'Home', myRoom: 'My Room', profile: 'Profile' },
  common: {
    back: 'Back',
    next: 'Next',
    save: 'Save',
    skip: 'Skip',
    loading: 'Loading…',
    signOut: 'Sign out',
  },
  errors: {
    generic: 'Something went wrong. Try again.',
    handle_taken: 'That handle is taken. Try another.',
    invalid_handle: 'Handles are 3–20 letters, numbers or underscores.',
    invalid_display_name: 'Names are 1–30 characters.',
    consent_required: 'Your account is waiting for a parent’s OK.',
    room_not_allowed: 'You can’t study in that room.',
    invalid_note: 'Notes are 3–140 characters.',
    note_not_possible: 'That note can’t be added any more.',
    load_failed: 'Couldn’t reach the server. Check your connection.',
  },
  unconfigured: {
    title: 'Not connected yet',
    body: 'This build has no Supabase project. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local (or to the Vercel project settings) and rebuild.',
  },
  signIn: {
    title: 'Come study with us',
    lead: 'A cozy room you share with friends. See who’s studying right now.',
    google: 'Continue with Google',
    or: 'or',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    emailButton: 'Email me a sign-in link',
    sent: (email: string) => `Check ${email} for a sign-in link. You can close this tab.`,
    privacy: 'No ads, no tracking. Your email is only used to sign you in.',
  },
  onboarding: {
    step: (n: number, of: number) => `Step ${n} of ${of}`,
    age: {
      title: 'A couple of quick questions',
      countryLabel: 'Where do you live?',
      ageLabel: 'How old are you?',
      brackets: { under_13: 'Under 13', '13': '13', '14': '14', '15': '15', '16-17': '16–17', '18+': '18+' },
      why: 'Some countries need a parent’s OK below a certain age. We don’t store your birthday.',
    },
    name: {
      title: 'What should people call you?',
      handleLabel: 'Handle',
      handleHint: 'Lowercase letters, numbers and _. Your friends find you with it.',
      displayLabel: 'Display name',
      displayHint: 'Shown above your bean.',
      errors: {
        too_short: 'At least 3 characters.',
        too_long: 'Too long.',
        bad_chars: 'Only a–z, 0–9 and _.',
        empty: 'Pick a name.',
      },
    },
    bean: {
      title: 'Make your bean',
      skin: 'Skin',
      hair: 'Hair',
      body: 'Body',
      top: 'Top',
      randomize: 'Surprise me',
      finish: 'Finish',
    },
  },
  blocked: {
    title: 'Studyroom is for ages 13 and up',
    body: 'Sorry! We’ve removed the sign-in you just made. Come back when you’re 13.',
  },
  waiting: {
    title: 'Waiting for your parent',
    body: 'Where you live, a parent or guardian needs to say OK before you can use Studyroom. Asking them by email arrives in the next update.',
  },
  home: {
    greeting: { day: 'Good to see you.', night: 'The lamps are on.' },
    hi: (name: string) => `Hi, ${name}.`,
    soloTitle: 'Study solo',
    soloBody: 'Your own room, your own timer.',
    soloButton: 'Open my room',
    roomsHeading: 'Your rooms',
    emptyTitle: 'No shared rooms yet',
    emptyBody:
      'Rooms are where you study with friends. Creating and joining rooms arrives in the next update.',
    createRoom: 'Create room',
    joinWithCode: 'Join with code',
    comingSoon: 'Arrives in the next update',
  },
  room: {
    soloBadge: 'Just you',
    pomodoro: 'Pomodoro',
    stopwatch: 'Stopwatch',
    minutes: (m: number) => `${m} min`,
    statusLabel: 'What are you working on?',
    statusPlaceholder: 'e.g. HL Chem IA — data analysis',
    start: 'Start',
    end: 'End',
    endEarly: 'End early',
    focusing: 'Focusing',
    breakTitle: (m: number) => `Break · ${m} min`,
    breakBody: 'Stretch, drink some water, look out a window.',
    startNext: 'Start next focus',
    skipBreak: 'Skip break',
    checkinTitle: 'Still studying?',
    checkinBody: (mmss: string) => `Tap within ${mmss} or this session ends where you left it.`,
    checkinButton: 'Yes, still here',
  },
  endSheet: {
    title: 'Nice work',
    focused: (mmss: string) => `You focused for ${mmss}.`,
    noteLabel: 'What did you get done?',
    notePlaceholder: 'e.g. finished the data table for Q3',
    noteHint: 'Private to you. 3–140 characters.',
    saveNote: 'Save note',
    later: 'Later',
  },
  myRoom: {
    title: 'My Room',
    body: 'Your own little room. You’ll decorate it with what you earn from studying.',
  },
  profile: {
    title: 'Profile',
    lifetime: 'Lifetime',
    thisWeek: 'This week',
    streak: 'Day streak',
    historyTitle: 'History',
    historyEmpty: 'Finished sessions show up here.',
    addNote: 'Add a note',
    voided: 'Voided',
    privacy: 'Privacy',
  },
  notFound: { title: 'This room does not exist', back: 'Back home' },
} as const

/** Message for an RPC error code; unknown codes get the generic message. */
export function errorMessage(code: string): string {
  return (copy.errors as Record<string, string | undefined>)[code] ?? copy.errors.generic
}
