// Every user-facing string lives here (SPEC §16).
export const copy = {
  tabs: { home: 'Home', myRoom: 'My Room', profile: 'Profile' },
  common: {
    back: 'Back',
    next: 'Next',
    save: 'Save',
    skip: 'Skip',
    loading: 'Loading…',
    signOut: 'Sign out',
  },
  errors: {
    generic: 'Something went wrong. Try again.',
    handle_taken: 'That handle is taken. Try another.',
    invalid_handle: 'Handles are 3–20 letters, numbers or underscores.',
    invalid_display_name: 'Names are 1–30 characters.',
    consent_required: 'Your account is waiting for a parent’s OK.',
    room_not_allowed: 'You can’t study in that room.',
    invalid_note: 'Notes are 3–140 characters.',
    note_not_possible: 'That note can’t be added any more.',
    load_failed: 'Couldn’t reach the server. Check your connection.',
    inappropriate_text: 'Let’s keep it friendly. Try different words.',
    room_not_found: 'That room doesn’t exist, or its invite link changed.',
    room_full: 'That room is full (50 people).',
    too_many_rooms: 'You’re in 20 rooms already. Leave one first.',
    too_many_rooms_created: 'You’ve created 10 rooms already.',
    banned_from_room: 'You were removed from this room.',
    rate_limited: 'Slow down a little and try again in a minute.',
    owner_must_transfer: 'Hand the room to someone else before you leave.',
    not_allowed: 'Only the room’s owner or mods can do that.',
    invalid_room_name: 'Room names are 3–40 characters.',
    invalid_reason: 'Give a short reason (3–140 characters).',
    invalid_email: 'That doesn’t look like an email address.',
    parent_email_is_yours: 'Use your parent’s or guardian’s email, not yours.',
    too_many_requests: 'You’ve asked three times. Check with your parent directly.',
    consent_not_found: 'This link isn’t valid any more.',
    consent_expired: 'This request expired. Your child can ask again from the app.',
    account_banned: 'This account can’t use Studyroom.',
  },
  loadError: {
    body: 'Your sign-in worked, but loading your profile failed. Try again in a moment.',
    schemaTitle: 'The database isn’t set up yet',
    schemaBody:
      'Sign-in worked, but the Studyroom tables aren’t in this Supabase project. Apply the migrations (supabase db push), then try again.',
    retry: 'Try again',
  },
  unconfigured: {
    title: 'Not connected yet',
    body: 'This build has no Supabase project. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local (or to the Vercel project settings) and rebuild.',
  },
  signIn: {
    title: 'Come study with us',
    lead: 'A cozy room you share with friends. See who’s studying right now.',
    google: 'Continue with Google',
    or: 'or',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    emailButton: 'Email me a sign-in link',
    sent: (email: string) => `Check ${email} for a sign-in link. You can close this tab.`,
    privacy: 'No ads, no tracking. Your email is only used to sign you in.',
  },
  onboarding: {
    step: (n: number, of: number) => `Step ${n} of ${of}`,
    age: {
      title: 'A couple of quick questions',
      countryLabel: 'Where do you live?',
      ageLabel: 'How old are you?',
      brackets: { under_13: 'Under 13', '13': '13', '14': '14', '15': '15', '16-17': '16–17', '18+': '18+' },
      why: 'Some countries need a parent’s OK below a certain age. We don’t store your birthday.',
    },
    name: {
      title: 'What should people call you?',
      handleLabel: 'Handle',
      handleHint: 'Lowercase letters, numbers and _. Your friends find you with it.',
      displayLabel: 'Display name',
      displayHint: 'Shown above your bean.',
      errors: {
        too_short: 'At least 3 characters.',
        too_long: 'Too long.',
        bad_chars: 'Only a–z, 0–9 and _.',
        empty: 'Pick a name.',
      },
    },
    bean: {
      title: 'Make your bean',
      skin: 'Skin',
      hair: 'Hair',
      body: 'Body',
      top: 'Top',
      randomize: 'Surprise me',
      finish: 'Finish',
    },
  },
  blocked: {
    title: 'Studyroom is for ages 13 and up',
    body: 'Sorry! We’ve removed the sign-in you just made. Come back when you’re 13.',
  },
  waiting: {
    title: 'Waiting for your parent',
    body: 'Where you live, a parent or guardian needs to say OK before you can use Studyroom. We’ll email them a link to review and decide.',
    emailLabel: 'Parent or guardian’s email',
    send: 'Send the request',
    resend: 'Send again',
    sent: (email: string) => `Sent to ${email}. It can take a few minutes; ask them to check spam too.`,
    expiry: 'If nobody answers within 7 days, this account is deleted.',
    deleteInstead: 'Delete my account instead',
  },
  consent: {
    title: (name: string) => `${name} would like to use Studyroom`,
    lead: 'Studyroom is a study timer where friends see each other studying in shared rooms.',
    collect: [
      'We collect: an email address (only to sign in), a display name, a cartoon avatar, and study sessions (start time, length, an optional note).',
      'Room members see display names, avatars and study minutes. There is no chat.',
      'No ads, no tracking, no selling data. You can withdraw at any time, which deletes the account.',
    ],
    agree: 'I’m their parent or guardian and I agree',
    decline: 'Decline',
    withdraw: 'Withdraw consent and delete the account',
    granted: 'Thank you. The account is active.',
    deleted: 'Done. The account and its data have been deleted.',
    expired: 'This request has expired.',
    privacy: 'Read the full privacy page',
  },
  home: {
    greeting: { day: 'Good to see you.', night: 'The lamps are on.' },
    hi: (name: string) => `Hi, ${name}.`,
    today: 'Today',
    thisWeek: 'This week',
    streak: 'Day streak',
    streakDays: (n: number) => (n === 1 ? '1 day' : `${n} days`),
    soloTitle: 'Study solo',
    soloBody: 'Your own room, your own timer.',
    soloButton: 'Open my room',
    roomsHeading: 'Your rooms',
    emptyTitle: 'No shared rooms yet',
    emptyBody: 'Rooms are where you study with friends. Make one and send the link, or join with a code.',
    createRoom: 'Create room',
    joinWithCode: 'Join with code',
    studyingNow: (n: number) =>
      n === 0 ? 'Nobody studying' : n === 1 ? '1 studying now' : `${n} studying now`,
    members: (n: number) => (n === 1 ? '1 member' : `${n} members`),
    createTitle: 'Create a room',
    nameLabel: 'Room name',
    namePlaceholder: 'e.g. IB Chem crew',
    create: 'Create',
    joinTitle: 'Join a room',
    codeLabel: 'Invite code or link',
    join: 'Join',
    cancel: 'Cancel',
  },
  invite: {
    title: (name: string) => `Join ${name}`,
    members: (n: number) => (n === 1 ? '1 member' : `${n} members`),
    studyingNow: 'Studying right now',
    nobody: 'Nobody’s studying right now. Be the first.',
    join: 'Join the room',
    signInFirst: 'Sign in to join',
    notFound: 'This invite link doesn’t work any more. Ask for a new one.',
  },
  theme: {
    title: 'Theme',
    mode: { auto: 'Auto', light: 'Light', dark: 'Dark' },
    autoHint: 'Auto follows the time of day: light by day, lamp-lit at night.',
  },
  room: {
    soloBadge: 'Just you',
    present: (n: number) => (n === 1 ? '1 here' : `${n} here`),
    alone: (time: string) => `You’ve got the room to yourself · ${time}`,
    nightOwl: (time: string) => `Night owl — you’ve had the room to yourself for ${time}`,
    emptyRoom: 'Nobody’s studying yet. Start a timer and you’ll be the first one here.',
    sat: (name: string) => `${name} just sat down`,
    onBreak: 'On a break',
    focusingLabel: 'Focusing',
    menu: 'Room menu',
    invite: 'Invite friends',
    copyLink: 'Copy invite link',
    copied: 'Link copied',
    share: 'Share',
    settings: 'Room settings',
    leave: 'Leave room',
    leaveConfirm: 'Leave this room? Your study time stays on its boards.',
    tabs: { leaderboard: 'Leaderboard', members: 'Members' },
    boards: { live: 'Now', week: 'Week', alltime: 'All-time', lifetime: 'Lifetime' },
    boardHint: {
      live: 'Minutes in the current sitting.',
      week: 'Minutes in this room since Monday.',
      alltime: 'Every minute in this room.',
      lifetime: 'Every minute anywhere, for people in this room.',
    },
    boardEmpty: 'No minutes yet.',
    you: 'you',
    reactions: 'Reactions',
    nudge: 'Nudge',
    nudged: (name: string) => `${name} nudged you 👋`,
    reacted: (name: string, emoji: string) => `${name} ${emoji}`,
    block: 'Block',
    unblock: 'Unblock',
    report: 'Report',
    removed: 'You were removed from this room.',
    freeDesk: 'free desk',
    sceneLoading: 'Setting up the room…',
    sceneLabel: (name: string) => `${name}, isometric room view`,
    label: (name: string, state: string, clock: string) => `${name}, ${state}, ${clock}`,
    presentNow: 'Here now',
    everyone: 'Everyone',
    onlineIdle: (names: string[]) =>
      `${names.join(', ')} ${names.length === 1 ? 'is' : 'are'} here, not studying yet.`,
    sittingDots: (n: number) => (n === 1 ? '1 pomodoro this sitting' : `${n} pomodoros this sitting`),
    todayTotal: (time: string) => `Today: ${time}`,
    pomodoro: 'Pomodoro',
    stopwatch: 'Stopwatch',
    minutes: (m: number) => `${m} min`,
    statusLabel: 'What are you working on?',
    statusPlaceholder: 'e.g. HL Chem IA — data analysis',
    start: 'Start',
    end: 'End',
    endEarly: 'End early',
    focusing: 'Focusing',
    breakTitle: (m: number) => `Break · ${m} min`,
    breakBody: 'Stretch, drink some water, look out a window.',
    startNext: 'Start next focus',
    skipBreak: 'Skip break',
    checkinTitle: 'Still studying?',
    checkinBody: (mmss: string) => `Tap within ${mmss} or this session ends where you left it.`,
    checkinButton: 'Yes, still here',
  },
  profileSheet: {
    weekMinutes: (m: string) => `${m} this week`,
    roleOwner: 'Owner',
    roleMod: 'Mod',
    makeMod: 'Make mod',
    removeMod: 'Remove mod',
    makeOwner: 'Make owner',
    remove: 'Remove from room',
    removeConfirm: (name: string) => `Remove ${name}? They can’t rejoin with the link.`,
    sessions: 'Recent sessions',
    void: 'Void',
    voidReason: 'Why? (shown to them)',
    voided: 'Voided',
  },
  reportSheet: {
    title: (name: string) => `Report ${name}`,
    reasonLabel: 'What’s wrong?',
    reasons: {
      harassment: 'Being mean or harassing',
      inappropriate_name: 'Inappropriate name or text',
      cheating: 'Cheating on the timer',
      unfair_void: 'An unfair void',
      other: 'Something else',
    },
    noteLabel: 'Anything else? (optional)',
    send: 'Send report',
    sent: 'Thanks. The room’s owner and the Studyroom admin will look at it.',
  },
  settingsSheet: {
    title: 'Room settings',
    rename: 'Room name',
    save: 'Save',
    newLink: 'Make a new invite link',
    newLinkHint: 'The old link stops working.',
    reports: 'Open reports',
    noReports: 'No open reports.',
  },
  endSheet: {
    title: 'Nice work',
    focused: (mmss: string) => `You focused for ${mmss}.`,
    noteLabel: 'What did you get done?',
    notePlaceholder: 'e.g. finished the data table for Q3',
    noteHint: 'Private to you. 3–140 characters.',
    saveNote: 'Save note',
    later: 'Later',
  },
  myRoom: {
    title: 'My Room',
    body: 'Your own little room. Soon you’ll decorate it with what you earn from studying.',
    studyHere: 'Study here',
    editBean: 'Change bean',
    beanTitle: 'Your bean',
    save: 'Save',
    saved: 'Bean updated',
    sceneLabel: (name: string) => `${name}’s room`,
  },
  profile: {
    title: 'Profile',
    lifetime: 'Lifetime',
    thisWeek: 'This week',
    streak: 'Day streak',
    historyTitle: 'History',
    historyEmpty: 'Finished sessions show up here.',
    addNote: 'Add a note',
    voided: 'Voided',
    privacy: 'Privacy',
    account: 'Your account',
    weekChart: 'Focus, last 7 days',
    export: 'Download my data',
    deleteAccount: 'Delete my account',
    deleteConfirm: (handle: string) =>
      `This deletes your account, sessions and notes for good. Type ${handle} to confirm.`,
    deleteButton: 'Delete forever',
    blocked: 'Blocked people',
    noneBlocked: 'Nobody blocked.',
    admin: 'Moderation queue',
  },
  admin: {
    title: 'Moderation queue',
    empty: 'No open reports.',
    dismiss: 'Dismiss',
    removeContent: 'Remove content',
    ban: 'Ban user',
    deleteRoom: 'Delete room',
    confirm: (action: string) => `${action}? This can’t be undone.`,
  },
  privacy: {
    title: 'Privacy',
    updated: 'Last updated 9 October 2026',
  },
  notFound: { title: 'This room does not exist', back: 'Back home' },
} as const

/** Message for an RPC error code; unknown codes get the generic message. */
export function errorMessage(code: string): string {
  return (copy.errors as Record<string, string | undefined>)[code] ?? copy.errors.generic
}
