// Generated by scripts/design/themes.mjs — theme picker previews and meta theme-color.
export const THEME_PREVIEWS = {
  lamplight: {
    label: 'Lamplight',
    light: {
      bg: '#ECE3D3',
      surface: '#FBF7F0',
      accent: '#FFC86B',
      nav: '#2F3A5C',
    },
    dark: {
      bg: '#2F3A5C',
      surface: '#F6EFE4',
      accent: '#FFC86B',
      nav: '#222B47',
    },
  },
  library: {
    label: 'Library',
    light: {
      bg: '#DCE5D3',
      surface: '#FAF7EC',
      accent: '#E0B04F',
      nav: '#1E3A2F',
    },
    dark: {
      bg: '#1E3A2F',
      surface: '#F3EEDC',
      accent: '#E0B04F',
      nav: '#152B22',
    },
  },
  blossom: {
    label: 'Blossom',
    light: {
      bg: '#F5E1E7',
      surface: '#FFFAFB',
      accent: '#F49CB3',
      nav: '#3E2440',
    },
    dark: {
      bg: '#3E2440',
      surface: '#FFF6F8',
      accent: '#F49CB3',
      nav: '#2E1A30',
    },
  },
  observatory: {
    label: 'Observatory',
    light: {
      bg: '#E3E5F2',
      surface: '#FFFFFF',
      accent: '#B9A7F2',
      nav: '#161A2E',
    },
    dark: {
      bg: '#161A2E',
      surface: '#232847',
      accent: '#B9A7F2',
      nav: '#10132A',
    },
  },
} as const
