-- M8 "study hub" (decision 0014): expressions, room styles, more starter things, Discover, moving
-- between rooms, and all-time stats.

-- ---------------------------------------------------------------------------
-- Expressions: a free face per bean (src/content/avatar.ts EXPRESSIONS)
-- ---------------------------------------------------------------------------
create or replace function private.valid_avatar(a jsonb) returns boolean
language sql immutable set search_path = '' as $$
  select coalesce(
    jsonb_typeof(a) = 'object'
    and (select bool_and(k in ('colors', 'hair', 'outfit', 'accessories', 'expression')) from jsonb_object_keys(a) k)
    and jsonb_typeof(a -> 'colors') = 'object'
    and (select bool_and(k in ('body', 'skin', 'hair', 'top', 'accent')) from jsonb_object_keys(a -> 'colors') k)
    and (select bool_and(coalesce(a -> 'colors' ->> k, '') ~ '^#[0-9a-fA-F]{6}$')
           from unnest(array['body', 'skin', 'hair', 'top']) as k)
    and (a -> 'colors' -> 'accent' is null or coalesce(a -> 'colors' ->> 'accent', '') ~ '^#[0-9a-fA-F]{6}$')
    and (a -> 'hair' is null or coalesce(a ->> 'hair', '') in ('short', 'long', 'curly', 'bun'))
    and (a -> 'expression' is null or coalesce(a ->> 'expression', '') in
          ('happy', 'joyful', 'calm', 'focused', 'sleepy', 'surprised', 'cheeky', 'cat'))
    and (a -> 'outfit' is null or (
          jsonb_typeof(a -> 'outfit') = 'object'
          and (select coalesce(bool_and(k in ('top', 'bottom')), true) from jsonb_object_keys(a -> 'outfit') k)
          and (a -> 'outfit' -> 'top' is null or coalesce(a -> 'outfit' ->> 'top', '') in ('tee', 'hoodie', 'stripes', 'collar'))
          and (a -> 'outfit' -> 'bottom' is null or coalesce(a -> 'outfit' ->> 'bottom', '') in ('trousers', 'shorts', 'skirt'))))
    and (a -> 'accessories' is null or (
          jsonb_typeof(a -> 'accessories') = 'array'
          and jsonb_array_length(a -> 'accessories') <= 4
          and (select coalesce(bool_and(jsonb_typeof(x) = 'string' and x #>> '{}' in
                 ('beanie', 'cap', 'bow', 'glasses', 'headphones', 'scarf', 'beret', 'cat_ears', 'flower', 'shades')), true)
                 from jsonb_array_elements(a -> 'accessories') as x)
          -- one per slot: head (hats, bow, beret, cat ears, flower) and face (glasses, shades)
          and (select count(*) from jsonb_array_elements_text(a -> 'accessories') as x
                where x in ('beanie', 'cap', 'bow', 'beret', 'cat_ears', 'flower')) <= 1
          and (select count(*) from jsonb_array_elements_text(a -> 'accessories') as x
                where x in ('glasses', 'shades')) <= 1
          and (select count(*) from jsonb_array_elements_text(a -> 'accessories') as x)
            = (select count(distinct x) from jsonb_array_elements_text(a -> 'accessories') as x)))
    and pg_column_size(a) < 2048,
    false)
$$;

-- ---------------------------------------------------------------------------
-- Fuller rooms: more starter things for everyone (src/content/catalog.json "starter"). Existing
-- accounts and rooms get the difference, on top of whatever they bought.
-- ---------------------------------------------------------------------------
create temp table m8_old_starter as select scope, item_id, qty from public.catalog_starter;

-- catalog:begin (generated by scripts/catalog/generate.mjs from src/content/catalog.json; do not edit by hand)
insert into public.catalog_items (id, name, category, price, footprint_w, footprint_d, layer, model, seat, slot) values
  ('desk_oak', 'Oak desk', 'furniture', 120, 1, 1, 'floor', 'desk', false, null),
  ('desk_white', 'White desk', 'furniture', 160, 1, 1, 'floor', 'desk', false, null),
  ('chair_wood', 'Wooden chair', 'furniture', 60, 1, 1, 'floor', 'chair', true, null),
  ('chair_red', 'Red chair', 'furniture', 90, 1, 1, 'floor', 'chair', true, null),
  ('stool', 'Stool', 'furniture', 50, 1, 1, 'floor', 'stool', true, null),
  ('armchair', 'Armchair', 'furniture', 300, 1, 1, 'floor', 'armchair', true, null),
  ('beanbag', 'Beanbag', 'furniture', 180, 1, 1, 'floor', 'beanbag', true, null),
  ('sofa', 'Sofa', 'furniture', 450, 2, 1, 'floor', 'sofa', true, null),
  ('bookshelf', 'Bookshelf', 'furniture', 220, 2, 1, 'floor', 'bookshelf', false, null),
  ('bookshelf_tall', 'Tall bookcase', 'furniture', 160, 1, 1, 'floor', 'tallshelf', false, null),
  ('side_table', 'Side table', 'furniture', 70, 1, 1, 'floor', 'sidetable', false, null),
  ('bed', 'Bed', 'furniture', 600, 2, 3, 'floor', 'bed', false, null),
  ('crate', 'Crate', 'furniture', 30, 1, 1, 'floor', 'crate', false, null),
  ('lamp_floor', 'Floor lamp', 'decor', 90, 1, 1, 'floor', 'lamp', false, null),
  ('plant_pot', 'Potted plant', 'decor', 40, 1, 1, 'floor', 'plant', false, null),
  ('plant_tall', 'Tall plant', 'decor', 120, 1, 1, 'floor', 'tallplant', false, null),
  ('cactus', 'Cactus', 'decor', 35, 1, 1, 'floor', 'cactus', false, null),
  ('globe', 'Globe', 'decor', 140, 1, 1, 'floor', 'globe', false, null),
  ('book_pile', 'Pile of books', 'decor', 25, 1, 1, 'floor', 'bookpile', false, null),
  ('radio', 'Radio', 'decor', 110, 1, 1, 'floor', 'radio', false, null),
  ('fish_tank', 'Fish tank', 'decor', 900, 1, 1, 'floor', 'fishtank', false, null),
  ('cat', 'Sleepy cat', 'decor', 800, 1, 1, 'floor', 'cat', false, null),
  ('telescope', 'Telescope', 'decor', 1500, 1, 1, 'floor', 'telescope', false, null),
  ('rug_stripe', 'Striped rug', 'decor', 80, 3, 3, 'rug', 'rug', false, null),
  ('rug_long', 'Big rug', 'decor', 140, 4, 6, 'rug', 'rug', false, null),
  ('rug_round', 'Round rug', 'decor', 120, 3, 3, 'rug', 'roundrug', false, null),
  ('window_double', 'Window', 'wall', 150, 2, 1, 'wall', 'window', false, null),
  ('poster', 'Poster', 'wall', 45, 1, 1, 'wall', 'poster', false, null),
  ('clock', 'Wall clock', 'wall', 75, 1, 1, 'wall', 'clock', false, null),
  ('corkboard', 'Corkboard', 'wall', 95, 2, 1, 'wall', 'corkboard', false, null),
  ('wall_shelf', 'Wall shelf', 'wall', 130, 2, 1, 'wall', 'wallshelf', false, null),
  ('fairy_lights', 'Fairy lights', 'wall', 200, 3, 1, 'wall', 'lights', false, null),
  ('whiteboard', 'Whiteboard', 'wall', 160, 2, 1, 'wall', 'whiteboard', false, null),
  ('beret', 'Beret', 'accessory', 250, null, null, null, null, false, 'head'),
  ('cat_ears', 'Cat ears', 'accessory', 400, null, null, null, null, false, 'head'),
  ('flower', 'Flower clip', 'accessory', 150, null, null, null, null, false, 'head'),
  ('shades', 'Sunglasses', 'accessory', 300, null, null, null, null, false, 'face')
on conflict (id) do update set name = excluded.name, category = excluded.category, price = excluded.price,
  footprint_w = excluded.footprint_w, footprint_d = excluded.footprint_d, layer = excluded.layer,
  model = excluded.model, seat = excluded.seat, slot = excluded.slot;
delete from public.catalog_starter;
insert into public.catalog_starter (scope, item_id, qty) values
  ('personal', 'rug_stripe', 1),
  ('personal', 'desk_oak', 1),
  ('personal', 'chair_wood', 1),
  ('personal', 'lamp_floor', 1),
  ('personal', 'plant_pot', 1),
  ('personal', 'window_double', 1),
  ('personal', 'bookshelf_tall', 1),
  ('personal', 'plant_tall', 1),
  ('personal', 'beanbag', 1),
  ('personal', 'book_pile', 1),
  ('personal', 'side_table', 1),
  ('personal', 'poster', 1),
  ('personal', 'clock', 1),
  ('personal', 'corkboard', 1),
  ('shared', 'rug_long', 1),
  ('shared', 'desk_oak', 4),
  ('shared', 'chair_wood', 4),
  ('shared', 'bookshelf', 1),
  ('shared', 'window_double', 1),
  ('shared', 'plant_pot', 2),
  ('shared', 'plant_tall', 1),
  ('shared', 'lamp_floor', 2),
  ('shared', 'beanbag', 2),
  ('shared', 'side_table', 1),
  ('shared', 'book_pile', 1),
  ('shared', 'radio', 1),
  ('shared', 'whiteboard', 1),
  ('shared', 'corkboard', 1),
  ('shared', 'clock', 1),
  ('shared', 'poster', 1),
  ('shared', 'wall_shelf', 1),
  ('shared', 'fairy_lights', 1);
-- catalog:end

insert into public.inventory (user_id, item_id, qty)
select p.id, s.item_id, s.qty - coalesce(o.qty, 0)
  from public.profiles p
  cross join public.catalog_starter s
  left join m8_old_starter o on o.scope = s.scope and o.item_id = s.item_id
 where s.scope = 'personal' and s.qty > coalesce(o.qty, 0)
on conflict (user_id, item_id) do update set qty = public.inventory.qty + excluded.qty;
insert into public.room_inventory (room_id, item_id, qty)
select r.id, s.item_id, s.qty - coalesce(o.qty, 0)
  from public.rooms r
  cross join public.catalog_starter s
  left join m8_old_starter o on o.scope = s.scope and o.item_id = s.item_id
 where s.scope = 'shared' and not r.is_personal and s.qty > coalesce(o.qty, 0)
on conflict (room_id, item_id) do update set qty = public.room_inventory.qty + excluded.qty;
drop table m8_old_starter;

-- ---------------------------------------------------------------------------
-- Room styles: wall and floor finishes (src/content/roomStyles.ts), free, per room
-- ---------------------------------------------------------------------------
alter table public.rooms add column style jsonb not null default '{}';
alter table public.rooms add column listed boolean not null default false;

create function private.valid_room_style(s jsonb) returns boolean
language sql immutable set search_path = '' as $$
  select coalesce(
    jsonb_typeof(s) = 'object'
    and (select coalesce(bool_and(k in ('wall', 'floor')), true) from jsonb_object_keys(s) k)
    and (s -> 'wall' is null or coalesce(s ->> 'wall', '') in
          ('theme', 'cream', 'sage', 'sky', 'blush', 'lavender', 'mint', 'navy', 'terracotta'))
    and (s -> 'floor' is null or coalesce(s ->> 'floor', '') in
          ('theme', 'oak', 'birch', 'walnut', 'cherry', 'slate', 'chalk')),
    false)
$$;
revoke all on function private.valid_room_style(jsonb) from public, anon, authenticated;
alter table public.rooms add constraint rooms_style_check check (private.valid_room_style(style));

create function public.set_room_style(p_room_id uuid, p_wall text, p_floor text) returns void
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := private.active_uid();
  v_room public.rooms;
begin
  select * into v_room from public.rooms where id = p_room_id;
  if not found then
    raise exception 'room_not_found' using errcode = 'P0002';
  end if;
  if v_room.is_personal then
    if v_room.owner_id <> v_uid then
      raise exception 'not_allowed' using errcode = '42501';
    end if;
  else
    perform private.require_role(p_room_id, 'owner', 'mod');
  end if;
  if private.over_limit('style', 20, 600) then
    raise exception 'rate_limited' using errcode = '54000';
  end if;
  begin
    update public.rooms set style = jsonb_build_object('wall', coalesce(p_wall, 'theme'), 'floor', coalesce(p_floor, 'theme'))
     where id = p_room_id;
  exception when check_violation then
    raise exception 'invalid_style' using errcode = '22023';
  end;
  if not v_room.is_personal then
    perform private.broadcast(p_room_id, 'layout', '{}'::jsonb);
  end if;
end;
$$;
revoke all on function public.set_room_style(uuid, text, text) from public, anon;
grant execute on function public.set_room_style(uuid, text, text) to authenticated;

-- room_info and visit_room return the style too.
create or replace function public.room_info(p_room_id uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not private.am_member(p_room_id) then
    raise exception 'not_a_member' using errcode = '42501';
  end if;
  return (
    select jsonb_build_object(
      'sync_pomodoro', r.sync_pomodoro, 'sync_focus_s', r.sync_focus_s, 'sync_break_s', r.sync_break_s,
      'sync_epoch', r.sync_epoch, 'notify_active', m.notify_active, 'layout', r.layout, 'bank_coins', r.bank_coins,
      'station_id', r.station_id, 'style', r.style, 'listed', r.listed)
      from public.rooms r join public.room_members m on m.room_id = r.id and m.user_id = (select auth.uid())
     where r.id = p_room_id
  );
end;
$$;

create or replace function public.visit_room(p_user_id uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_uid uuid := private.active_uid();
begin
  if p_user_id <> v_uid and (
       not exists (select 1 from public.room_members a join public.room_members b on b.room_id = a.room_id
                    join public.rooms r on r.id = a.room_id
                   where a.user_id = v_uid and b.user_id = p_user_id and not a.banned and not b.banned and not r.is_personal)
       or exists (select 1 from public.blocks
                   where (blocker_id = v_uid and blocked_id = p_user_id) or (blocker_id = p_user_id and blocked_id = v_uid))
       or not exists (select 1 from public.profiles where id = p_user_id and consent_status in ('not_required', 'granted'))) then
    raise exception 'not_allowed' using errcode = '42501';
  end if;
  return (select jsonb_build_object('display_name', p.display_name, 'avatar', p.avatar, 'layout', r.layout, 'style', r.style)
            from public.profiles p join public.rooms r on r.owner_id = p.id and r.is_personal
           where p.id = p_user_id);
end;
$$;

-- ---------------------------------------------------------------------------
-- All-time stats for the Stats tab: your own completed sessions, in your timezone
-- ---------------------------------------------------------------------------
create function public.my_stats() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_uid uuid := private.active_uid();
  v_tz text;
begin
  select tz into v_tz from public.profiles where id = v_uid;
  if not exists (select 1 from pg_catalog.pg_timezone_names where name = v_tz) then
    v_tz := 'UTC';
  end if;
  return (
    with done as (
      select s.started_at at time zone v_tz as local, coalesce(s.focus_seconds, 0) as secs, s.kind, s.room_id,
             s.planned_seconds
        from public.sessions s
       where s.user_id = v_uid and s.status = 'completed'
    ), days as (
      select (local::date) as d, sum(secs)::int as s from done
       where local >= (now() at time zone v_tz)::date - 370
       group by 1
    ), months as (
      select to_char(date_trunc('month', local), 'YYYY-MM') as m, sum(secs)::int as s from done
       where local >= date_trunc('month', now() at time zone v_tz) - interval '11 months'
       group by 1
    ), rooms as (
      select case when r.is_personal then null else r.name end as name, r.is_personal, sum(d.secs)::int as s
        from done d join public.rooms r on r.id = d.room_id
       group by r.id, r.name, r.is_personal
       order by 3 desc
       limit 6
    )
    select jsonb_build_object(
      'tz', v_tz,
      'total_seconds', coalesce((select sum(secs) from done), 0),
      'sessions', (select count(*) from done),
      'pomodoros', (select count(*) from done where kind = 'pomodoro' and secs >= 1200),
      'longest_seconds', coalesce((select max(secs) from done), 0),
      'first_day', (select to_char(min(local), 'YYYY-MM-DD') from done),
      'days', coalesce((select jsonb_agg(jsonb_build_object('d', to_char(d, 'YYYY-MM-DD'), 's', s) order by d) from days), '[]'),
      'months', coalesce((select jsonb_agg(jsonb_build_object('m', m, 's', s) order by m) from months), '[]'),
      'hours', (select jsonb_agg(coalesce((select sum(secs) from done where extract(hour from local) = h), 0)::int order by h)
                  from generate_series(0, 23) h),
      'weekdays', (select jsonb_agg(coalesce((select sum(secs) from done where extract(isodow from local) = w), 0)::int order by w)
                     from generate_series(1, 7) w),
      'rooms', coalesce((select jsonb_agg(jsonb_build_object('name', name, 'personal', is_personal, 's', s)) from rooms), '[]')
    )
  );
end;
$$;
revoke all on function public.my_stats() from public, anon;
grant execute on function public.my_stats() to authenticated;

-- ---------------------------------------------------------------------------
-- Discover (decision 0014): owners may list a room; people of the same age band can find and join
-- it. A listed room shows only its name and counts (never members' names or faces) until you join.
-- ---------------------------------------------------------------------------
create index rooms_listed_idx on public.rooms (listed) where listed;

-- 13–15, 16–17 and adults never see each other's listed rooms.
create function private.age_band(p_bracket text) returns text
language sql immutable set search_path = '' as $$
  select case when p_bracket in ('13', '14', '15') then 'young' when p_bracket = '16-17' then 'older' else 'adult' end
$$;

-- A listed room is discoverable by you only if every member is in your age band and nobody there
-- has blocked you (or been blocked by you).
create function private.discoverable(p_room_id uuid, p_uid uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.rooms r
     where r.id = p_room_id and r.listed and not r.is_personal
       and not exists (select 1 from public.room_members m where m.room_id = r.id and m.user_id = p_uid)
       and not exists (
         select 1 from public.room_members m join public.profiles p on p.id = m.user_id
          where m.room_id = r.id and not m.banned
            and private.age_band(p.age_bracket) <> (select private.age_band(age_bracket) from public.profiles where id = p_uid))
       and not exists (
         select 1 from public.room_members m join public.blocks b
             on (b.blocker_id = m.user_id and b.blocked_id = p_uid) or (b.blocker_id = p_uid and b.blocked_id = m.user_id)
          where m.room_id = r.id)
       and (select count(*) from public.room_members m where m.room_id = r.id and not m.banned) < 50)
$$;
revoke all on function private.discoverable(uuid, uuid) from public, anon, authenticated;

create function public.set_room_listed(p_room_id uuid, p_listed boolean) returns void
language plpgsql security definer set search_path = '' as $$
declare v_uid uuid := private.require_role(p_room_id, 'owner');
begin
  if p_listed and exists (
       select 1 from public.room_members m join public.profiles p on p.id = m.user_id
        where m.room_id = p_room_id and not m.banned
          and private.age_band(p.age_bracket) <> (select private.age_band(age_bracket) from public.profiles where id = v_uid)) then
    raise exception 'mixed_ages' using errcode = '22023';
  end if;
  update public.rooms set listed = coalesce(p_listed, false) where id = p_room_id and not is_personal;
end;
$$;

create function public.discover_rooms() returns table (
  id uuid, name text, member_count int, studying_count int, sync_pomodoro boolean
)
language plpgsql stable security definer set search_path = '' as $$
declare v_uid uuid := private.active_uid();
begin
  return query
    select r.id, r.name,
           (select count(*)::int from public.room_members m where m.room_id = r.id and not m.banned),
           (select count(*)::int from public.sessions s where s.room_id = r.id and s.status = 'active'),
           r.sync_pomodoro
      from public.rooms r
     where r.listed and private.discoverable(r.id, v_uid)
     order by 4 desc, 3 desc, r.created_at desc
     limit 30;
end;
$$;

create function public.join_listed_room(p_room_id uuid) returns public.rooms
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := private.active_uid();
  v_code text;
begin
  if not private.discoverable(p_room_id, v_uid) then
    raise exception 'room_not_found' using errcode = 'P0002';
  end if;
  select invite_code into v_code from public.rooms where id = p_room_id;
  return public.join_room(v_code); -- same checks and limits as an invite link
end;
$$;

revoke all on function public.set_room_listed(uuid, boolean) from public, anon;
grant execute on function public.set_room_listed(uuid, boolean) to authenticated;
revoke all on function public.discover_rooms() from public, anon;
grant execute on function public.discover_rooms() to authenticated;
revoke all on function public.join_listed_room(uuid) from public, anon;
grant execute on function public.join_listed_room(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Moving rooms: you study in one room at a time, but can carry a running session to another of
-- your rooms. The whole session then counts in the new room (decision 0014).
-- ---------------------------------------------------------------------------
create function public.move_session(p_room_id uuid) returns public.sessions
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := private.active_uid();
  v_room public.rooms;
  s public.sessions;
  v_from uuid;
begin
  if private.over_limit('move', 20, 600) then
    raise exception 'rate_limited' using errcode = '54000';
  end if;
  if not private.can_study_in(p_room_id, v_uid) then
    raise exception 'room_not_allowed' using errcode = '42501';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(v_uid::text, 0));
  select * into s from public.sessions where user_id = v_uid and status = 'active' for update;
  if not found then
    raise exception 'no_active_session' using errcode = 'P0002';
  end if;
  if s.room_id = p_room_id then
    return s;
  end if;
  select * into v_room from public.rooms where id = p_room_id;
  -- A shared-pomodoro room runs its own clock: join its next focus instead of bringing yours.
  if v_room.sync_pomodoro and not v_room.is_personal then
    raise exception 'sync_room_move' using errcode = '22023';
  end if;
  v_from := s.room_id;
  update public.sessions set room_id = p_room_id, sitting_id = gen_random_uuid()
   where id = s.id
  returning * into s;
  perform private.broadcast(v_from, 'state', jsonb_build_object('user_id', v_uid));
  perform private.broadcast(p_room_id, 'state', jsonb_build_object('user_id', v_uid));
  return s;
end;
$$;
revoke all on function public.move_session(uuid) from public, anon;
grant execute on function public.move_session(uuid) to authenticated;
