-- M5: coins, room banks, the shop, inventories, decorating (save_layout) and visiting (SPEC §6.5, §8, §10).
-- Every balance is a sum of a ledger; clients only ever call RPCs (CLAUDE.md: no client writes of coins,
-- inventory or layouts).

-- ---------------------------------------------------------------------------
-- Catalog (seeded from src/content/catalog.json by scripts/catalog/generate.mjs)
-- ---------------------------------------------------------------------------
create table public.catalog_items (
  id text primary key check (id ~ '^[a-z0-9_]{2,30}$'),
  name text not null check (char_length(name) between 1 and 40),
  category text not null check (category in ('furniture', 'decor', 'wall', 'accessory')),
  price int not null check (price between 20 and 1500),
  footprint_w int check (footprint_w between 1 and 6),
  footprint_d int check (footprint_d between 1 and 6),
  layer text check (layer in ('floor', 'rug', 'wall')),
  model text,
  seat boolean not null default false,
  slot text check (slot in ('head', 'face')),
  constraint catalog_shape check (
    (category = 'accessory') = (footprint_w is null and footprint_d is null and layer is null and slot is not null)
  )
);
alter table public.catalog_items enable row level security;
revoke all on table public.catalog_items from anon, authenticated;
grant select on table public.catalog_items to authenticated;
create policy catalog_items_read on public.catalog_items for select to authenticated using (true);

-- What every new person (personal room) and every new shared room owns from the start.
create table public.catalog_starter (
  scope text not null check (scope in ('personal', 'shared')),
  item_id text not null references public.catalog_items (id),
  qty int not null check (qty > 0),
  primary key (scope, item_id)
);
alter table public.catalog_starter enable row level security;
revoke all on table public.catalog_starter from anon, authenticated;

-- catalog:begin (generated by scripts/catalog/generate.mjs from src/content/catalog.json; do not edit by hand)
insert into public.catalog_items (id, name, category, price, footprint_w, footprint_d, layer, model, seat, slot) values
  ('desk_oak', 'Oak desk', 'furniture', 120, 1, 1, 'floor', 'desk', false, null),
  ('desk_white', 'White desk', 'furniture', 160, 1, 1, 'floor', 'desk', false, null),
  ('chair_wood', 'Wooden chair', 'furniture', 60, 1, 1, 'floor', 'chair', true, null),
  ('chair_red', 'Red chair', 'furniture', 90, 1, 1, 'floor', 'chair', true, null),
  ('stool', 'Stool', 'furniture', 50, 1, 1, 'floor', 'stool', true, null),
  ('armchair', 'Armchair', 'furniture', 300, 1, 1, 'floor', 'armchair', true, null),
  ('beanbag', 'Beanbag', 'furniture', 180, 1, 1, 'floor', 'beanbag', true, null),
  ('sofa', 'Sofa', 'furniture', 450, 2, 1, 'floor', 'sofa', true, null),
  ('bookshelf', 'Bookshelf', 'furniture', 220, 2, 1, 'floor', 'bookshelf', false, null),
  ('bookshelf_tall', 'Tall bookcase', 'furniture', 160, 1, 1, 'floor', 'tallshelf', false, null),
  ('side_table', 'Side table', 'furniture', 70, 1, 1, 'floor', 'sidetable', false, null),
  ('bed', 'Bed', 'furniture', 600, 2, 3, 'floor', 'bed', false, null),
  ('crate', 'Crate', 'furniture', 30, 1, 1, 'floor', 'crate', false, null),
  ('lamp_floor', 'Floor lamp', 'decor', 90, 1, 1, 'floor', 'lamp', false, null),
  ('plant_pot', 'Potted plant', 'decor', 40, 1, 1, 'floor', 'plant', false, null),
  ('plant_tall', 'Tall plant', 'decor', 120, 1, 1, 'floor', 'tallplant', false, null),
  ('cactus', 'Cactus', 'decor', 35, 1, 1, 'floor', 'cactus', false, null),
  ('globe', 'Globe', 'decor', 140, 1, 1, 'floor', 'globe', false, null),
  ('book_pile', 'Pile of books', 'decor', 25, 1, 1, 'floor', 'bookpile', false, null),
  ('radio', 'Radio', 'decor', 110, 1, 1, 'floor', 'radio', false, null),
  ('fish_tank', 'Fish tank', 'decor', 900, 1, 1, 'floor', 'fishtank', false, null),
  ('cat', 'Sleepy cat', 'decor', 800, 1, 1, 'floor', 'cat', false, null),
  ('telescope', 'Telescope', 'decor', 1500, 1, 1, 'floor', 'telescope', false, null),
  ('rug_stripe', 'Striped rug', 'decor', 80, 3, 3, 'rug', 'rug', false, null),
  ('rug_long', 'Big rug', 'decor', 140, 4, 6, 'rug', 'rug', false, null),
  ('rug_round', 'Round rug', 'decor', 120, 3, 3, 'rug', 'roundrug', false, null),
  ('window_double', 'Window', 'wall', 150, 2, 1, 'wall', 'window', false, null),
  ('poster', 'Poster', 'wall', 45, 1, 1, 'wall', 'poster', false, null),
  ('clock', 'Wall clock', 'wall', 75, 1, 1, 'wall', 'clock', false, null),
  ('corkboard', 'Corkboard', 'wall', 95, 2, 1, 'wall', 'corkboard', false, null),
  ('wall_shelf', 'Wall shelf', 'wall', 130, 2, 1, 'wall', 'wallshelf', false, null),
  ('fairy_lights', 'Fairy lights', 'wall', 200, 3, 1, 'wall', 'lights', false, null),
  ('whiteboard', 'Whiteboard', 'wall', 160, 2, 1, 'wall', 'whiteboard', false, null),
  ('beret', 'Beret', 'accessory', 250, null, null, null, null, false, 'head'),
  ('cat_ears', 'Cat ears', 'accessory', 400, null, null, null, null, false, 'head'),
  ('flower', 'Flower clip', 'accessory', 150, null, null, null, null, false, 'head'),
  ('shades', 'Sunglasses', 'accessory', 300, null, null, null, null, false, 'face')
on conflict (id) do update set name = excluded.name, category = excluded.category, price = excluded.price,
  footprint_w = excluded.footprint_w, footprint_d = excluded.footprint_d, layer = excluded.layer,
  model = excluded.model, seat = excluded.seat, slot = excluded.slot;
delete from public.catalog_starter;
insert into public.catalog_starter (scope, item_id, qty) values
  ('personal', 'rug_stripe', 1),
  ('personal', 'desk_oak', 1),
  ('personal', 'chair_wood', 1),
  ('personal', 'lamp_floor', 1),
  ('personal', 'plant_pot', 1),
  ('personal', 'window_double', 1),
  ('shared', 'rug_long', 1),
  ('shared', 'desk_oak', 4),
  ('shared', 'chair_wood', 4),
  ('shared', 'bookshelf', 1),
  ('shared', 'window_double', 1);
-- catalog:end

-- ---------------------------------------------------------------------------
-- Ledgers and inventories
-- ---------------------------------------------------------------------------
create table public.coin_ledger (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  delta int not null check (delta <> 0),
  reason text not null check (reason in ('session', 'bonus', 'purchase', 'donate', 'void', 'admin')),
  ref uuid,
  created_at timestamptz not null default now()
);
create index coin_ledger_user_idx on public.coin_ledger (user_id, created_at);
create index coin_ledger_ref_idx on public.coin_ledger (ref) where ref is not null;
alter table public.coin_ledger enable row level security;
revoke all on table public.coin_ledger from anon, authenticated;
grant select on table public.coin_ledger to authenticated;
create policy coin_ledger_own on public.coin_ledger for select to authenticated using (user_id = (select auth.uid()));

create table public.room_bank_ledger (
  id bigint generated always as identity primary key,
  room_id uuid not null references public.rooms (id) on delete cascade,
  user_id uuid references public.profiles (id) on delete set null,
  delta int not null check (delta <> 0),
  reason text not null check (reason in ('study', 'donate', 'purchase', 'void')),
  ref uuid,
  created_at timestamptz not null default now()
);
create index room_bank_ledger_room_idx on public.room_bank_ledger (room_id, created_at);
create index room_bank_ledger_ref_idx on public.room_bank_ledger (ref) where ref is not null;
alter table public.room_bank_ledger enable row level security;
revoke all on table public.room_bank_ledger from anon, authenticated;
grant select on table public.room_bank_ledger to authenticated;
create policy room_bank_ledger_members on public.room_bank_ledger for select to authenticated
  using ((select private.am_member(room_id)));

create table public.inventory (
  user_id uuid not null references public.profiles (id) on delete cascade,
  item_id text not null references public.catalog_items (id),
  qty int not null check (qty >= 0),
  primary key (user_id, item_id)
);
alter table public.inventory enable row level security;
revoke all on table public.inventory from anon, authenticated;
grant select on table public.inventory to authenticated;
create policy inventory_own on public.inventory for select to authenticated using (user_id = (select auth.uid()));

create table public.room_inventory (
  room_id uuid not null references public.rooms (id) on delete cascade,
  item_id text not null references public.catalog_items (id),
  qty int not null check (qty >= 0),
  primary key (room_id, item_id)
);
alter table public.room_inventory enable row level security;
revoke all on table public.room_inventory from anon, authenticated;
grant select on table public.room_inventory to authenticated;
create policy room_inventory_members on public.room_inventory for select to authenticated
  using ((select private.am_member(room_id)));

-- rooms.bank_coins follows its ledger (SPEC §8.1).
create function private.bank_follow_ledger() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  update public.rooms set bank_coins = bank_coins + new.delta where id = new.room_id;
  return new;
end;
$$;
create trigger room_bank_ledger_follow after insert on public.room_bank_ledger
  for each row execute function private.bank_follow_ledger();

create function private.balance(p_uid uuid) returns int
language sql stable security definer set search_path = '' as $$
  select coalesce(sum(delta), 0)::int from public.coin_ledger where user_id = p_uid
$$;

-- Starter items: for new people and new shared rooms, and for everyone who exists already.
create function private.grant_starter_personal() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.inventory (user_id, item_id, qty)
  select new.id, s.item_id, s.qty from public.catalog_starter s where s.scope = 'personal'
  on conflict do nothing;
  return new;
end;
$$;
create trigger profiles_starter_inventory after insert on public.profiles
  for each row execute function private.grant_starter_personal();

create function private.grant_starter_shared() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if not new.is_personal then
    insert into public.room_inventory (room_id, item_id, qty)
    select new.id, s.item_id, s.qty from public.catalog_starter s where s.scope = 'shared'
    on conflict do nothing;
  end if;
  return new;
end;
$$;
create trigger rooms_starter_inventory after insert on public.rooms
  for each row execute function private.grant_starter_shared();

insert into public.inventory (user_id, item_id, qty)
select p.id, s.item_id, s.qty from public.profiles p cross join public.catalog_starter s where s.scope = 'personal'
on conflict do nothing;
insert into public.room_inventory (room_id, item_id, qty)
select r.id, s.item_id, s.qty from public.rooms r cross join public.catalog_starter s
 where s.scope = 'shared' and not r.is_personal
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- Earning (SPEC §6.5): 1 coin per focus minute + 5 for a full pomodoro of 20+ min, with a note;
-- at most 720 a day in the person's timezone. Shared rooms also fill their bank.
-- ---------------------------------------------------------------------------
create function private.session_coins(p_focus_s int, p_kind text, p_planned_s int)
returns table (minutes int, bonus int)
language sql immutable set search_path = '' as $$
  select greatest(coalesce(p_focus_s, 0), 0) / 60,
         case when p_kind = 'pomodoro' and coalesce(p_planned_s, 0) >= 1200
                   and coalesce(p_focus_s, 0) >= coalesce(p_planned_s, 0) then 5 else 0 end
$$;

create or replace function public.submit_note(p_session_id uuid, p_note text, p_public boolean default false) returns int
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := private.active_uid();
  v_note text := btrim(p_note);
  s public.sessions;
  v_tz text;
  v_today int;
  v_left int;
  v_min int;
  v_bonus int;
  v_paid int := 0;
begin
  if char_length(v_note) not between 3 and 140 then
    raise exception 'invalid_note' using errcode = '22023';
  end if;
  if coalesce(p_public, false) then
    perform private.require_clean(v_note); -- shown to the room, so filtered like every public text
  end if;
  update public.sessions
     set note = v_note, note_public = coalesce(p_public, false)
   where id = p_session_id and user_id = v_uid and status = 'completed' and note is null
     and ended_at >= now() - interval '24 hours'
  returning * into s;
  if not found then
    raise exception 'note_not_possible' using errcode = 'P0002';
  end if;
  insert into public.events (user_id, name) values (v_uid, 'note_submitted');

  if not s.coins_paid then
    select tz into v_tz from public.profiles where id = v_uid;
    if not exists (select 1 from pg_catalog.pg_timezone_names where name = v_tz) then
      v_tz := 'UTC';
    end if;
    -- Serialise per person so two notes at once can't both slip under the daily cap.
    perform pg_advisory_xact_lock(hashtextextended('coins:' || v_uid::text, 0));
    select coalesce(sum(delta), 0)::int into v_today from public.coin_ledger
     where user_id = v_uid and reason in ('session', 'bonus')
       and created_at >= (date_trunc('day', now() at time zone v_tz)) at time zone v_tz;
    v_left := greatest(720 - v_today, 0);
    select c.minutes, c.bonus into v_min, v_bonus from private.session_coins(s.focus_seconds, s.kind, s.planned_seconds) c;
    v_min := least(v_min, v_left);
    v_bonus := least(v_bonus, v_left - v_min);
    if v_min > 0 then
      insert into public.coin_ledger (user_id, delta, reason, ref) values (v_uid, v_min, 'session', s.id);
    end if;
    if v_bonus > 0 then
      insert into public.coin_ledger (user_id, delta, reason, ref) values (v_uid, v_bonus, 'bonus', s.id);
    end if;
    update public.sessions set coins_paid = true where id = s.id;
    v_paid := v_min + v_bonus;
  end if;
  return v_paid;
end;
$$;

-- Room bank auto-fill: half a coin per focus minute in shared rooms, at most 360 per member per room per
-- day (room timezone), on top of the member's own earnings. Voiding reverses both.
create function private.sessions_coin_effects() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_room public.rooms;
  v_today int;
  v_add int;
  v_back int;
begin
  if new.status = 'completed' and old.status = 'active' then
    select * into v_room from public.rooms where id = new.room_id;
    if not v_room.is_personal then
      select coalesce(sum(delta), 0)::int into v_today from public.room_bank_ledger
       where room_id = new.room_id and user_id = new.user_id and reason = 'study'
         and created_at >= (date_trunc('day', now() at time zone v_room.tz)) at time zone v_room.tz;
      v_add := least(coalesce(new.focus_seconds, 0) / 120, greatest(360 - v_today, 0));
      if v_add > 0 then
        insert into public.room_bank_ledger (room_id, user_id, delta, reason, ref)
        values (new.room_id, new.user_id, v_add, 'study', new.id);
      end if;
    end if;
  elsif new.status = 'voided' and old.status <> 'voided' then
    select coalesce(sum(delta), 0)::int into v_back from public.coin_ledger
     where ref = new.id and reason in ('session', 'bonus', 'void');
    if v_back > 0 then
      insert into public.coin_ledger (user_id, delta, reason, ref) values (new.user_id, -v_back, 'void', new.id);
    end if;
    select coalesce(sum(delta), 0)::int into v_back from public.room_bank_ledger
     where ref = new.id and reason in ('study', 'void');
    if v_back > 0 then
      insert into public.room_bank_ledger (room_id, user_id, delta, reason, ref)
      values (new.room_id, new.user_id, -v_back, 'void', new.id);
    end if;
  end if;
  return new;
end;
$$;
create trigger sessions_coin_effects after update of status on public.sessions
  for each row execute function private.sessions_coin_effects();

-- ---------------------------------------------------------------------------
-- Spending
-- ---------------------------------------------------------------------------
create function public.my_wallet() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_uid uuid := private.active_uid();
  v_tz text;
begin
  select tz into v_tz from public.profiles where id = v_uid;
  if not exists (select 1 from pg_catalog.pg_timezone_names where name = v_tz) then
    v_tz := 'UTC';
  end if;
  return jsonb_build_object(
    'balance', private.balance(v_uid),
    'earned_today', (select coalesce(sum(delta), 0) from public.coin_ledger
                      where user_id = v_uid and reason in ('session', 'bonus')
                        and created_at >= (date_trunc('day', now() at time zone v_tz)) at time zone v_tz),
    'daily_cap', 720
  );
end;
$$;

create function public.buy_item(p_item_id text, p_qty int default 1) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := private.active_uid();
  v_item public.catalog_items;
  v_qty int := coalesce(p_qty, 1);
  v_cost int;
begin
  select * into v_item from public.catalog_items where id = p_item_id;
  if not found then
    raise exception 'unknown_item' using errcode = 'P0002';
  end if;
  if v_qty not between 1 and 10 or (v_item.category = 'accessory' and v_qty <> 1) then
    raise exception 'invalid_qty' using errcode = '22023';
  end if;
  if v_item.category = 'accessory'
     and exists (select 1 from public.inventory where user_id = v_uid and item_id = p_item_id and qty > 0) then
    raise exception 'already_owned' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('coins:' || v_uid::text, 0));
  v_cost := v_item.price * v_qty;
  if private.balance(v_uid) < v_cost then
    raise exception 'not_enough_coins' using errcode = '22023';
  end if;
  insert into public.coin_ledger (user_id, delta, reason) values (v_uid, -v_cost, 'purchase');
  insert into public.inventory (user_id, item_id, qty) values (v_uid, p_item_id, v_qty)
  on conflict (user_id, item_id) do update set qty = public.inventory.qty + excluded.qty;
  insert into public.events (user_id, name, props)
  values (v_uid, 'item_bought', jsonb_build_object('category', v_item.category, 'price', v_item.price));
  return jsonb_build_object('balance', private.balance(v_uid));
end;
$$;

create function public.donate(p_room_id uuid, p_amount int) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := private.active_uid();
begin
  if not private.am_member(p_room_id) or (select is_personal from public.rooms where id = p_room_id) then
    raise exception 'not_a_member' using errcode = '42501';
  end if;
  if coalesce(p_amount, 0) not between 1 and 10000 then
    raise exception 'invalid_amount' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('coins:' || v_uid::text, 0));
  if private.balance(v_uid) < p_amount then
    raise exception 'not_enough_coins' using errcode = '22023';
  end if;
  insert into public.coin_ledger (user_id, delta, reason, ref) values (v_uid, -p_amount, 'donate', p_room_id);
  insert into public.room_bank_ledger (room_id, user_id, delta, reason) values (p_room_id, v_uid, p_amount, 'donate');
  insert into public.events (user_id, name, props) values (v_uid, 'donated', jsonb_build_object('amount', p_amount));
  return jsonb_build_object('balance', private.balance(v_uid),
                            'bank', (select bank_coins from public.rooms where id = p_room_id));
end;
$$;

create function public.room_buy_item(p_room_id uuid, p_item_id text, p_qty int default 1) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := private.require_role(p_room_id, 'owner', 'mod');
  v_item public.catalog_items;
  v_bank int;
  v_qty int := coalesce(p_qty, 1);
begin
  select * into v_item from public.catalog_items where id = p_item_id;
  if not found or v_item.category = 'accessory' then
    raise exception 'unknown_item' using errcode = 'P0002';
  end if;
  if v_qty not between 1 and 10 then
    raise exception 'invalid_qty' using errcode = '22023';
  end if;
  select bank_coins into v_bank from public.rooms where id = p_room_id and not is_personal for update;
  if not found then
    raise exception 'not_allowed' using errcode = '42501';
  end if;
  if v_bank < v_item.price * v_qty then
    raise exception 'not_enough_coins' using errcode = '22023';
  end if;
  insert into public.room_bank_ledger (room_id, user_id, delta, reason)
  values (p_room_id, v_uid, -(v_item.price * v_qty), 'purchase');
  insert into public.room_inventory (room_id, item_id, qty) values (p_room_id, p_item_id, v_qty)
  on conflict (room_id, item_id) do update set qty = public.room_inventory.qty + excluded.qty;
  return jsonb_build_object('bank', (select bank_coins from public.rooms where id = p_room_id));
end;
$$;

-- ---------------------------------------------------------------------------
-- Decorating: save_layout mirrors src/core/grid.ts (shared vectors in src/core/__fixtures__/layouts.json)
-- ---------------------------------------------------------------------------
create function private.layout_error(p_layout jsonb, p_size int) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  it jsonb;
  idx int := -1;
  v_def public.catalog_items;
  v_x numeric;
  v_z numeric;
  v_rot numeric;
  v_w int;
  v_d int;
  v_along int;
  v_used text[] := '{}';
  v_slot text;
  i int;
  j int;
begin
  if jsonb_typeof(p_layout) <> 'array' or jsonb_array_length(p_layout) > 80 then
    return jsonb_build_object('error', 'bad_layout', 'index', 0);
  end if;
  for it in select value from jsonb_array_elements(p_layout) loop
    idx := idx + 1;
    select * into v_def from public.catalog_items
     where id = case when jsonb_typeof(it -> 'item_id') = 'string' then it ->> 'item_id' end
       and category <> 'accessory';
    if not found then
      return jsonb_build_object('error', 'unknown_item', 'index', idx);
    end if;
    if jsonb_typeof(it -> 'x') <> 'number' or jsonb_typeof(it -> 'z') <> 'number' or jsonb_typeof(it -> 'rot') <> 'number' then
      return jsonb_build_object('error', 'bad_position', 'index', idx);
    end if;
    v_x := (it ->> 'x')::numeric;
    v_z := (it ->> 'z')::numeric;
    v_rot := (it ->> 'rot')::numeric;
    if v_x <> trunc(v_x) or v_z <> trunc(v_z) or v_rot not in (0, 1, 2, 3) then
      return jsonb_build_object('error', 'bad_position', 'index', idx);
    end if;
    if v_def.layer = 'wall' then
      if v_rot > 1 or (case when v_rot = 0 then v_z else v_x end) <> 0 then
        return jsonb_build_object('error', 'bad_wall_slot', 'index', idx);
      end if;
      v_along := (case when v_rot = 0 then v_x else v_z end)::int;
      if v_along < 0 or v_along + v_def.footprint_w > p_size then
        return jsonb_build_object('error', 'out_of_bounds', 'index', idx);
      end if;
      for i in 0 .. v_def.footprint_w - 1 loop
        v_slot := 'wall' || v_rot::int || ':' || (v_along + i);
        if v_slot = any (v_used) then
          return jsonb_build_object('error', 'overlap', 'index', idx);
        end if;
        v_used := v_used || v_slot;
      end loop;
    else
      if mod(v_rot::int, 2) = 0 then
        v_w := v_def.footprint_w; v_d := v_def.footprint_d;
      else
        v_w := v_def.footprint_d; v_d := v_def.footprint_w;
      end if;
      if v_x < 0 or v_z < 0 or v_x + v_w > p_size or v_z + v_d > p_size then
        return jsonb_build_object('error', 'out_of_bounds', 'index', idx);
      end if;
      for i in 0 .. v_w - 1 loop
        for j in 0 .. v_d - 1 loop
          v_slot := v_def.layer || ':' || (v_x::int + i) || ',' || (v_z::int + j);
          if v_slot = any (v_used) then
            return jsonb_build_object('error', 'overlap', 'index', idx);
          end if;
          v_used := v_used || v_slot;
        end loop;
      end loop;
    end if;
  end loop;
  return null;
end;
$$;

create function public.save_layout(p_room_id uuid, p_layout jsonb) returns void
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := private.active_uid();
  v_room public.rooms;
  v_err jsonb;
  v_short text;
begin
  select * into v_room from public.rooms where id = p_room_id;
  if not found then
    raise exception 'room_not_found' using errcode = 'P0002';
  end if;
  if v_room.is_personal then
    if v_room.owner_id <> v_uid then
      raise exception 'not_allowed' using errcode = '42501';
    end if;
  else
    perform private.require_role(p_room_id, 'owner', 'mod');
  end if;
  v_err := private.layout_error(p_layout, case when v_room.is_personal then 8 else 12 end);
  if v_err is not null then
    raise exception 'invalid_layout' using errcode = '22023', detail = v_err::text;
  end if;
  -- You can only place what you (or the room) own.
  select u.item_id into v_short
    from (select x ->> 'item_id' as item_id, count(*) as n from jsonb_array_elements(p_layout) x group by 1) u
   where u.n > coalesce(case when v_room.is_personal
                         then (select qty from public.inventory where user_id = v_uid and item_id = u.item_id)
                         else (select qty from public.room_inventory where room_id = p_room_id and item_id = u.item_id) end, 0)
   limit 1;
  if v_short is not null then
    raise exception 'item_not_owned' using errcode = '22023', detail = v_short;
  end if;
  update public.rooms set layout = p_layout where id = p_room_id;
  if not v_room.is_personal then
    perform private.broadcast(p_room_id, 'layout', '{}'::jsonb);
  end if;
end;
$$;

-- Shop accessories must be owned to be worn (SPEC §8.3 save_avatar; enforced on every write path).
create function private.check_avatar_owned() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_missing text;
begin
  select a into v_missing
    from jsonb_array_elements_text(coalesce(new.avatar -> 'accessories', '[]')) a
    join public.catalog_items c on c.id = a and c.category = 'accessory'
   where not exists (select 1 from public.inventory i where i.user_id = new.id and i.item_id = a and i.qty > 0)
   limit 1;
  if v_missing is not null then
    raise exception 'accessory_not_owned' using errcode = '22023', detail = v_missing;
  end if;
  return new;
end;
$$;
create trigger profiles_avatar_owned before insert or update of avatar on public.profiles
  for each row execute function private.check_avatar_owned();

-- Avatars may now carry the shop accessories too (same rules as before otherwise).
create or replace function private.valid_avatar(a jsonb) returns boolean
language sql immutable set search_path = '' as $$
  select coalesce(
    jsonb_typeof(a) = 'object'
    and (select bool_and(k in ('colors', 'hair', 'outfit', 'accessories')) from jsonb_object_keys(a) k)
    and jsonb_typeof(a -> 'colors') = 'object'
    and (select bool_and(k in ('body', 'skin', 'hair', 'top', 'accent')) from jsonb_object_keys(a -> 'colors') k)
    and (select bool_and(coalesce(a -> 'colors' ->> k, '') ~ '^#[0-9a-fA-F]{6}$')
           from unnest(array['body', 'skin', 'hair', 'top']) as k)
    and (a -> 'colors' -> 'accent' is null or coalesce(a -> 'colors' ->> 'accent', '') ~ '^#[0-9a-fA-F]{6}$')
    and (a -> 'hair' is null or coalesce(a ->> 'hair', '') in ('short', 'long', 'curly', 'bun'))
    and (a -> 'outfit' is null or (
          jsonb_typeof(a -> 'outfit') = 'object'
          and (select coalesce(bool_and(k in ('top', 'bottom')), true) from jsonb_object_keys(a -> 'outfit') k)
          and (a -> 'outfit' -> 'top' is null or coalesce(a -> 'outfit' ->> 'top', '') in ('tee', 'hoodie', 'stripes', 'collar'))
          and (a -> 'outfit' -> 'bottom' is null or coalesce(a -> 'outfit' ->> 'bottom', '') in ('trousers', 'shorts', 'skirt'))))
    and (a -> 'accessories' is null or (
          jsonb_typeof(a -> 'accessories') = 'array'
          and jsonb_array_length(a -> 'accessories') <= 4
          and (select coalesce(bool_and(jsonb_typeof(x) = 'string' and x #>> '{}' in
                 ('beanie', 'cap', 'bow', 'glasses', 'headphones', 'scarf', 'beret', 'cat_ears', 'flower', 'shades')), true)
                 from jsonb_array_elements(a -> 'accessories') as x)
          -- one per slot: head (hats, bow, beret, cat ears, flower) and face (glasses, shades)
          and (select count(*) from jsonb_array_elements_text(a -> 'accessories') as x
                where x in ('beanie', 'cap', 'bow', 'beret', 'cat_ears', 'flower')) <= 1
          and (select count(*) from jsonb_array_elements_text(a -> 'accessories') as x
                where x in ('glasses', 'shades')) <= 1
          and (select count(*) from jsonb_array_elements_text(a -> 'accessories') as x)
            = (select count(distinct x) from jsonb_array_elements_text(a -> 'accessories') as x)))
    and pg_column_size(a) < 2048,
    false)
$$;

-- ---------------------------------------------------------------------------
-- Visiting a roommate's personal room (read-only; blocks either way hide it)
-- ---------------------------------------------------------------------------
create function public.visit_room(p_user_id uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_uid uuid := private.active_uid();
begin
  if p_user_id <> v_uid and (
       not exists (select 1 from public.room_members a join public.room_members b on b.room_id = a.room_id
                    join public.rooms r on r.id = a.room_id
                   where a.user_id = v_uid and b.user_id = p_user_id and not a.banned and not b.banned and not r.is_personal)
       or exists (select 1 from public.blocks
                   where (blocker_id = v_uid and blocked_id = p_user_id) or (blocker_id = p_user_id and blocked_id = v_uid))
       or not exists (select 1 from public.profiles where id = p_user_id and consent_status in ('not_required', 'granted'))) then
    raise exception 'not_allowed' using errcode = '42501';
  end if;
  return (select jsonb_build_object('display_name', p.display_name, 'avatar', p.avatar, 'layout', r.layout)
            from public.profiles p join public.rooms r on r.owner_id = p.id and r.is_personal
           where p.id = p_user_id);
end;
$$;

-- room_info gains the layout and bank, for the scene and the room shop.
create or replace function public.room_info(p_room_id uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not private.am_member(p_room_id) then
    raise exception 'not_a_member' using errcode = '42501';
  end if;
  return (
    select jsonb_build_object(
      'sync_pomodoro', r.sync_pomodoro, 'sync_focus_s', r.sync_focus_s, 'sync_break_s', r.sync_break_s,
      'sync_epoch', r.sync_epoch, 'notify_active', m.notify_active, 'layout', r.layout, 'bank_coins', r.bank_coins)
      from public.rooms r join public.room_members m on m.room_id = r.id and m.user_id = (select auth.uid())
     where r.id = p_room_id
  );
end;
$$;

-- Export: coins and things owned.
create or replace function public.export_my_data() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;
  return jsonb_build_object(
    'exported_at', now(),
    'account', (select jsonb_build_object('email', u.email, 'created_at', u.created_at) from auth.users u where u.id = v_uid),
    'profile', (select to_jsonb(p) - 'is_admin' from public.profiles p where p.id = v_uid),
    'rooms', coalesce((select jsonb_agg(jsonb_build_object('room', r.name, 'role', m.role, 'joined_at', m.joined_at,
                                                           'notify_active', m.notify_active))
                         from public.room_members m join public.rooms r on r.id = m.room_id where m.user_id = v_uid), '[]'),
    'personal_room_layout', (select layout from public.rooms where owner_id = v_uid and is_personal),
    'sessions', coalesce((select jsonb_agg(to_jsonb(s) - 'user_id' order by s.started_at)
                            from public.sessions s where s.user_id = v_uid), '[]'),
    'coins', coalesce((select jsonb_agg(jsonb_build_object('delta', c.delta, 'reason', c.reason, 'at', c.created_at) order by c.id)
                         from public.coin_ledger c where c.user_id = v_uid), '[]'),
    'inventory', coalesce((select jsonb_object_agg(i.item_id, i.qty) from public.inventory i where i.user_id = v_uid), '{}'),
    'blocks', coalesce((select jsonb_agg(b.blocked_id) from public.blocks b where b.blocker_id = v_uid), '[]'),
    'reports_filed', coalesce((select jsonb_agg(jsonb_build_object('type', r.target_type, 'reason', r.reason, 'at', r.created_at))
                                 from public.reports r where r.reporter_id = v_uid), '[]'),
    'push_devices', coalesce((select jsonb_agg(jsonb_build_object('service', split_part(ps.endpoint, '/', 3), 'added_at', ps.created_at))
                                from public.push_subscriptions ps where ps.user_id = v_uid), '[]'),
    'parental_consent', (select jsonb_build_object('granted_at', c.granted_at, 'expires_at', c.expires_at)
                           from public.parental_consents c where c.user_id = v_uid)
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
revoke all on function private.bank_follow_ledger() from public;
revoke all on function private.balance(uuid) from public;
revoke all on function private.grant_starter_personal() from public;
revoke all on function private.grant_starter_shared() from public;
revoke all on function private.session_coins(int, text, int) from public;
revoke all on function private.sessions_coin_effects() from public;
revoke all on function private.layout_error(jsonb, int) from public;
revoke all on function private.check_avatar_owned() from public;
revoke all on function public.my_wallet() from public, anon;
revoke all on function public.buy_item(text, int) from public, anon;
revoke all on function public.donate(uuid, int) from public, anon;
revoke all on function public.room_buy_item(uuid, text, int) from public, anon;
revoke all on function public.save_layout(uuid, jsonb) from public, anon;
revoke all on function public.visit_room(uuid) from public, anon;
revoke all on function public.submit_note(uuid, text, boolean) from public, anon;
revoke all on function public.room_info(uuid) from public, anon;
revoke all on function public.export_my_data() from public, anon;
grant execute on function public.my_wallet() to authenticated;
grant execute on function public.buy_item(text, int) to authenticated;
grant execute on function public.donate(uuid, int) to authenticated;
grant execute on function public.room_buy_item(uuid, text, int) to authenticated;
grant execute on function public.save_layout(uuid, jsonb) to authenticated;
grant execute on function public.visit_room(uuid) to authenticated;
grant execute on function public.submit_note(uuid, text, boolean) to authenticated;
grant execute on function public.room_info(uuid) to authenticated;
grant execute on function public.export_my_data() to authenticated;
